import '../models/question.dart';

/// Pre-seeded NCERT-verified questions for NcertScienceCh4Data
class NcertScienceCh4Data {
  static List<Question> get questions => [
    Question(
      id: "sci_ch4_p61_q01",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 61)] What is the electron dot structure and bonding nature of carbon dioxide (\$\\text{CO}_2\$)?",
      options: const [
        QuestionOption(id: "A", text: "Carbon shares two pairs of electrons with each of the two oxygen atoms, forming two double covalent bonds: \$:\\ddot{\\text{O}}=\\text{C}=\\ddot{\\text{O}}:\$.", isCorrect: true),
        QuestionOption(id: "B", text: "Carbon forms single covalent bonds with both oxygen atoms, leaving one oxygen atom with an incomplete octet: \$\\text{O}-\\text{C}-\\text{O}\$.", isCorrect: false),
        QuestionOption(id: "C", text: "Carbon completely transfers four electrons to two oxygen atoms, forming an ionic crystal lattice of \$\\text{C}^{4+}\$ and \$2\\text{O}^{2-}\$.", isCorrect: false),
        QuestionOption(id: "D", text: "Carbon shares three electron pairs with one oxygen and one single pair with the other: \$:\\text{O}\\equiv\\text{C}-\\ddot{\\text{O}}:\$.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Carbon shares two pairs of electrons with each of the two oxygen atoms, forming two double covalent bonds: \$:\\ddot{\\text{O}}=\\text{C}=\\ddot{\\text{O}}:\$.\n\nScientific Principle / Key Concept:\n• Carbon (\$Z=6\$, configuration \$2, 4\$) has 4 valence electrons and requires 4 more to attain neon octet.\n• Oxygen (\$Z=8\$, configuration \$2, 6\$) has 6 valence electrons and requires 2 more to attain neon octet.\n• In \$\\text{CO}_2\$, the central carbon atom shares 2 electrons with the left oxygen and 2 electrons with the right oxygen atom. Each oxygen contributes 2 electrons, resulting in two double covalent bonds (\$:\\ddot{\\text{O}}=\\text{C}=\\ddot{\\text{O}}:\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Single bonds violate the octet rule for both carbon and oxygen.\n• Option (C): Incorrect. \$\\text{CO}_2\$ is a covalent gas, not an ionic salt.\n• Option (D): Incorrect. The molecule has two symmetric double bonds.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 0),
    ),
    Question(
      id: "sci_ch4_p61_q02",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 61)] What is the structural arrangement and electron dot representation of a molecule of sulphur (\$\\text{S}_8\$) made up of eight sulphur atoms?",
      options: const [
        QuestionOption(id: "A", text: "Eight sulphur atoms are linked in a closed, puckered (crown-shaped) ring, with each sulphur atom sharing two single covalent bonds with adjacent atoms.", isCorrect: true),
        QuestionOption(id: "B", text: "Eight sulphur atoms form a linear open chain containing alternating single and double covalent bonds.", isCorrect: false),
        QuestionOption(id: "C", text: "A central sulphur atom is surrounded by seven peripheral sulphur atoms held by coordinate covalent bonds.", isCorrect: false),
        QuestionOption(id: "D", text: "Eight sulphur atoms are arranged in a flat planar square with quadruple covalent bonds.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Eight sulphur atoms are linked in a closed, puckered (crown-shaped) ring, with each sulphur atom sharing two single covalent bonds with adjacent atoms.\n\nScientific Principle / Key Concept:\n• Sulphur has atomic number 16 (electronic configuration: \$2, 8, 6\$).\n• Each sulphur atom has 6 valence electrons and requires 2 additional electrons to achieve an octet.\n• In the \$\\text{S}_8\$ molecule, eight sulphur atoms form a puckered crown-shaped ring. Each atom shares one electron pair with its left neighbor and one electron pair with its right neighbor, forming two single covalent bonds and leaving two lone pairs on each atom.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. \$\\text{S}_8\$ is a cyclic ring, not an open chain.\n• Option (C): Incorrect. There is no central sulphur atom; all 8 are equivalent in the ring.\n• Option (D): Incorrect. The geometry is non-planar (crown-shaped) with single bonds.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 1000),
    ),
    Question(
      id: "sci_ch4_p68_q01",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 68)] How many structural isomers can be drawn for pentane (\$\\text{C}_5\\text{H}_{12}\$)?",
      options: const [
        QuestionOption(id: "A", text: "3 structural isomers: n-pentane, isopentane (2-methylbutane), and neopentane (2,2-dimethylpropane)", isCorrect: true),
        QuestionOption(id: "B", text: "2 structural isomers: n-pentane and cyclopentane", isCorrect: false),
        QuestionOption(id: "C", text: "4 structural isomers including 3-methylbutane and neopentane", isCorrect: false),
        QuestionOption(id: "D", text: "5 structural isomers corresponding to five different carbon positions", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) 3 structural isomers: n-pentane, isopentane (2-methylbutane), and neopentane (2,2-dimethylpropane)\n\nScientific Principle / Key Concept:\nStructural isomers are compounds that have identical molecular formulae but different carbon skeletons (structures). For pentane (\$\\text{C}_5\\text{H}_{12}\$), three isomers exist:\n1. n-pentane: \$\\text{CH}_3-\\text{CH}_2-\\text{CH}_2-\\text{CH}_2-\\text{CH}_3\$ (straight continuous 5-carbon chain)\n2. Isopentane (2-methylbutane): \$\\text{CH}_3-\\text{CH}(\\text{CH}_3)-\\text{CH}_2-\\text{CH}_3\$ (4-carbon main chain with one methyl branch)\n3. Neopentane (2,2-dimethylpropane): \$\\text{C}(\\text{CH}_3)_4\$ (3-carbon main chain with two methyl branches)\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Cyclopentane is \$\\text{C}_5\\text{H}_{10}\$, not an isomer of \$\\text{C}_5\\text{H}_{12}\$.\n• Option (C): Incorrect. 3-methylbutane is the same compound as 2-methylbutane.\n• Option (D): Incorrect. Only 3 distinct structures can be formed.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 2000),
    ),
    Question(
      id: "sci_ch4_p68_q02",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 68)] What are the two unique properties of carbon that lead to the formation of millions of carbon compounds?",
      options: const [
        QuestionOption(id: "A", text: "Catenation (ability to form self-linking covalent bonds in long chains/rings) and Tetravalency (valency of four enabling bonds with multiple elements)", isCorrect: true),
        QuestionOption(id: "B", text: "High chemical radioactivity and extreme ionic reactivity with atmospheric nitrogen", isCorrect: false),
        QuestionOption(id: "C", text: "High electrical superconductivity and malleable metallic bonding", isCorrect: false),
        QuestionOption(id: "D", text: "Low melting point and tendency to undergo spontaneous nuclear fusion", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Catenation (ability to form self-linking covalent bonds in long chains/rings) and Tetravalency (valency of four enabling bonds with multiple elements)\n\nScientific Principle / Key Concept:\nThe two exceptional properties of carbon are:\n1. Catenation: Carbon has the unique ability to form strong, stable covalent bonds with other carbon atoms, giving rise to long chains, branched chains, and closed rings.\n2. Tetravalency: With a valency of 4, a carbon atom is capable of bonding with 4 other atoms of carbon or monovalent elements (like H, Cl) as well as heteroatoms (O, N, S).\nTogether with the small atomic size of carbon (enabling strong, stable bond formation), these properties account for the immense variety of organic compounds.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Carbon compounds are covalent and non-radioactive.\n• Option (C): Incorrect. Carbon is a non-metal.\n• Option (D): Incorrect. Nuclear fusion is unrelated to chemical bonding.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 3000),
    ),
    Question(
      id: "sci_ch4_p68_q03",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 68)] What is the molecular formula and bonding structure of cyclopentane?",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{C}_5\\text{H}_{10}\$, consisting of a cyclic ring of 5 carbon atoms, where each carbon is bonded to two adjacent carbons and two hydrogen atoms by single bonds.", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{C}_5\\text{H}_{12}\$, consisting of five carbon atoms arranged in an open pentagonal loop.", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{C}_5\\text{H}_8\$, containing alternating double bonds inside a planar five-membered ring.", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{C}_5\\text{H}_5\$, an aromatic ring with delocalized pi electrons.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{C}_5\\text{H}_{10}\$, consisting of a cyclic ring of 5 carbon atoms, where each carbon is bonded to two adjacent carbons and two hydrogen atoms by single bonds.\n\nScientific Principle / Key Concept:\n• Cyclopentane is a saturated cyclic hydrocarbon (cycloalkane).\n• The general formula for cycloalkanes is \$\\text{C}_n\\text{H}_{2n}\$. With \$n=5\$, its molecular formula is \$\\text{C}_5\\text{H}_{10}\$.\n• The five carbon atoms form a closed five-membered ring. Each carbon atom forms two C-C single bonds with adjacent carbon atoms and two C-H single bonds with hydrogen atoms, satisfying tetravalency.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. \$\\text{C}_5\\text{H}_{12}\$ is open-chain pentane.\n• Option (C): Incorrect. \$\\text{C}_5\\text{H}_8\$ has multiple bonds.\n• Option (D): Incorrect. Cyclopentane is not aromatic.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 4000),
    ),
    Question(
      id: "sci_ch4_p69_q04_i",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 69)] What is the structural formula of Ethanoic acid?",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{CH}_3-\\text{C}(=\\text{O})-\\text{OH}\$ (a 2-carbon carboxylic acid with a carbonyl and hydroxyl group on the terminal carbon)", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{CH}_3-\\text{CH}_2-\\text{OH}\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{H}-\\text{C}(=\\text{O})-\\text{OH}\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{CH}_3-\\text{C}(=\\text{O})-\\text{CH}_3\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{CH}_3-\\text{C}(=\\text{O})-\\text{OH}\$ (a 2-carbon carboxylic acid with a carbonyl and hydroxyl group on the terminal carbon)\n\nScientific Principle / Key Concept:\nEthanoic acid contains:\n• Root word 'eth-' \$\\rightarrow 2\$ carbon atoms.\n• Suffix '-oic acid' \$\\rightarrow\$ carboxylic acid functional group (\$-\\text{COOH}\$).\nStructure: \$\\text{CH}_3-\\text{COOH}\$. Carbon-1 is double-bonded to an oxygen atom and single-bonded to an \$-\\text{OH}\$ group, while Carbon-2 is single-bonded to three hydrogen atoms.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. This is ethanol.\n• Option (C): Incorrect. This is methanoic acid (1 carbon).\n• Option (D): Incorrect. This is propanone.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 5000),
    ),
    Question(
      id: "sci_ch4_p69_q04_ii",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 69)] Are structural isomers possible for bromopentane (\$\\text{C}_5\\text{H}_{11}\\text{Br}\$)?",
      options: const [
        QuestionOption(id: "A", text: "Yes, both position isomers (1-bromopentane, 2-bromopentane, 3-bromopentane) and chain isomers are possible.", isCorrect: true),
        QuestionOption(id: "B", text: "No, because halogens cannot form isomers in carbon chains exceeding three carbons.", isCorrect: false),
        QuestionOption(id: "C", text: "No, because bromine can only bond to the terminal carbon atom.", isCorrect: false),
        QuestionOption(id: "D", text: "Yes, but strictly 2 isomers exist because pentane only has two ends.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Yes, both position isomers (1-bromopentane, 2-bromopentane, 3-bromopentane) and chain isomers are possible.\n\nScientific Principle / Key Concept:\nStructural isomers for \$\\text{C}_5\\text{H}_{11}\\text{Br}\$ exist in abundance:\n1. Position isomers of straight chain:\n• 1-bromopentane: \$\\text{CH}_3\\text{CH}_2\\text{CH}_2\\text{CH}_2\\text{CH}_2\\text{Br}\$\n• 2-bromopentane: \$\\text{CH}_3\\text{CH}_2\\text{CH}_2\\text{CH}(\\text{Br})\\text{CH}_3\$\n• 3-bromopentane: \$\\text{CH}_3\\text{CH}_2\\text{CH}(\\text{Br})\\text{CH}_2\\text{CH}_3\$\n2. In addition, chain isomers based on branched skeletons (isopentyl and neopentyl) yield additional isomers (e.g., 1-bromo-2-methylbutane, 2-bromo-2-methylbutane, etc.).\nHence, structural isomers are definitely possible.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Halogenated alkanes exhibit extensive isomerism.\n• Option (C): Incorrect. Halogens bond to internal secondary and tertiary carbons as well.\n• Option (D): Incorrect. C-3 is unique and gives a 3rd straight-chain isomer.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 6000),
    ),
    Question(
      id: "sci_ch4_p69_q04_iii",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 69)] What is the structural formula of Butanone?",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{CH}_3-\\text{C}(=\\text{O})-\\text{CH}_2-\\text{CH}_3\$ (a four-carbon chain containing a carbonyl ketone group at carbon-2)", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{CH}_3-\\text{CH}_2-\\text{CH}_2-\\text{CHO}\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{CH}_3-\\text{CH}_2-\\text{CH}_2-\\text{CH}_2-\\text{OH}\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{CH}_3-\\text{CH}_2-\\text{COOH}\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{CH}_3-\\text{C}(=\\text{O})-\\text{CH}_2-\\text{CH}_3\$ (a four-carbon chain containing a carbonyl ketone group at carbon-2)\n\nScientific Principle / Key Concept:\n• Root word 'but-' denotes 4 carbon atoms.\n• Suffix '-one' denotes a ketone functional group (\$-\\text{CO}-\$).\nSince a ketone group must be attached to two carbon atoms, in a four-carbon chain the carbonyl carbon must be at C-2:\n\$\$\\text{CH}_3-\\text{CO}-\\text{CH}_2-\\text{CH}_3\$\$\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. This is butanal (aldehyde).\n• Option (C): Incorrect. This is butanol (alcohol).\n• Option (D): Incorrect. This is propanoic acid.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 7000),
    ),
    Question(
      id: "sci_ch4_p69_q04_iv",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 69)] What is the structural formula of Hexanal?",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{CH}_3-\\text{CH}_2-\\text{CH}_2-\\text{CH}_2-\\text{CH}_2-\\text{CHO}\$ (a 6-carbon chain with a terminal aldehyde group)", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{CH}_3-(\\text{CH}_2)_4-\\text{COOH}\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{CH}_3-(\\text{CH}_2)_3-\\text{CO}-\\text{CH}_3\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{CH}_3-(\\text{CH}_2)_4-\\text{CH}_2\\text{OH}\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{CH}_3-\\text{CH}_2-\\text{CH}_2-\\text{CH}_2-\\text{CH}_2-\\text{CHO}\$ (a 6-carbon chain with a terminal aldehyde group)\n\nScientific Principle / Key Concept:\n• 'Hex-' indicates a six-carbon parent chain.\n• '-al' indicates an aldehyde group (\$-CHO\$) located at the terminus (C-1).\nStructure: \$\\text{CH}_3-\\text{CH}_2-\\text{CH}_2-\\text{CH}_2-\\text{CH}_2-\\text{CHO}\$.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. This is hexanoic acid.\n• Option (C): Incorrect. This is hexan-2-one.\n• Option (D): Incorrect. This is hexan-1-ol.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 8000),
    ),
    Question(
      id: "sci_ch4_p69_q05_i",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 69)] What is the IUPAC name of the compound \$\\text{CH}_3-\\text{CH}_2-\\text{Br}\$?",
      options: const [
        QuestionOption(id: "A", text: "Bromoethane", isCorrect: true),
        QuestionOption(id: "B", text: "Bromomethane", isCorrect: false),
        QuestionOption(id: "C", text: "Bromopropane", isCorrect: false),
        QuestionOption(id: "D", text: "Ethane bromide", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Bromoethane\n\nScientific Principle / Key Concept:\n• The parent alkane has 2 carbon atoms \$\\rightarrow\$ 'ethane'.\n• Halogen substituent \$-\\text{Br}\$ is designated by prefix 'bromo-'.\n• IUPAC name: Bromoethane.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. 1-carbon haloalkane.\n• Option (C): Incorrect. 3-carbon haloalkane.\n• Option (D): Incorrect IUPAC naming syntax.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 9000),
    ),
    Question(
      id: "sci_ch4_p69_q05_ii",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 69)] What is the IUPAC name of the compound \$\\text{H}-\\text{CHO}\$ (or \$\\text{H}-\\text{C}(=\\text{O})-\\text{H}\$)?",
      options: const [
        QuestionOption(id: "A", text: "Methanal", isCorrect: true),
        QuestionOption(id: "B", text: "Ethanal", isCorrect: false),
        QuestionOption(id: "C", text: "Methanol", isCorrect: false),
        QuestionOption(id: "D", text: "Methanone", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Methanal\n\nScientific Principle / Key Concept:\n• One carbon atom \$\\rightarrow\$ 'methane'.\n• Aldehyde functional group (\$-CHO\$) \$\\rightarrow\$ suffix '-al'.\n• Replacing 'e' with 'al': Methane - e + al = Methanal (common name: formaldehyde).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Ethanal has 2 carbons.\n• Option (C): Incorrect. Methanol is an alcohol.\n• Option (D): Incorrect. A single-carbon ketone cannot exist.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 10000),
    ),
    Question(
      id: "sci_ch4_p69_q05_iii",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 69)] What is the IUPAC name of the unsaturated hydrocarbon \$\\text{H}-\\text{C}\\equiv\\text{C}-\\text{CH}_2-\\text{CH}_2-\\text{CH}_2-\\text{CH}_3\$?",
      options: const [
        QuestionOption(id: "A", text: "Hex-1-yne (or 1-hexyne)", isCorrect: true),
        QuestionOption(id: "B", text: "Hex-1-ene", isCorrect: false),
        QuestionOption(id: "C", text: "Pent-1-yne", isCorrect: false),
        QuestionOption(id: "D", text: "Hexane", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Hex-1-yne (or 1-hexyne)\n\nScientific Principle / Key Concept:\n• Longest chain contains 6 carbons \$\\rightarrow\$ 'hex'.\n• Functional group is an alkyne (carbon-carbon triple bond \$\\text{C}\\equiv\\text{C}\$) \$\\rightarrow\$ suffix '-yne'.\n• Numbering from the end closest to the triple bond gives position 1: Hex-1-yne (or 1-hexyne).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. '-ene' denotes a double bond.\n• Option (C): Incorrect. Chain length is 6, not 5.\n• Option (D): Incorrect. Hexane is saturated.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 11000),
    ),
    Question(
      id: "sci_ch4_p71_q01",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 71)] Why is the chemical conversion of ethanol to ethanoic acid classified as an oxidation reaction?",
      options: const [
        QuestionOption(id: "A", text: "One oxygen atom is added and two hydrogen atoms are removed from the ethanol molecule: \$\\text{CH}_3\\text{CH}_2\\text{OH} + 2[\\text{O}] \\rightarrow \\text{CH}_3\\text{COOH} + \\text{H}_2\\text{O}\$.", isCorrect: true),
        QuestionOption(id: "B", text: "Ethanol gains four hydrogen atoms from acidified potassium dichromate.", isCorrect: false),
        QuestionOption(id: "C", text: "The carbon chain is cleaved into two separate single-carbon units.", isCorrect: false),
        QuestionOption(id: "D", text: "Ethanol completely dehydrates into gaseous ethene without any oxygen transfer.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) One oxygen atom is added and two hydrogen atoms are removed from the ethanol molecule: \$\\text{CH}_3\\text{CH}_2\\text{OH} + 2[\\text{O}] \\rightarrow \\text{CH}_3\\text{COOH} + \\text{H}_2\\text{O}\$.\n\nScientific Principle / Key Concept:\nIn the reaction:\n\$\$\\text{CH}_3\\text{CH}_2\\text{OH} \\xrightarrow{\\text{Alkaline }\\text{KMnO}_4 + \\Delta\\text{ or Acidified }\\text{K}_2\\text{Cr}_2\\text{O}_7 + \\Delta} \\text{CH}_3\\text{COOH}\$\$\n1. Ethanol (\$\\text{C}_2\\text{H}_6\\text{O}\$) contains 1 oxygen atom and 6 hydrogen atoms.\n2. Ethanoic acid (\$\\text{C}_2\\text{H}_4\\text{O}_2\$) contains 2 oxygen atoms and 4 hydrogen atoms.\nSince oxygen is added and hydrogen is removed, the process is an oxidation reaction.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Gaining hydrogen is reduction.\n• Option (C): Incorrect. Carbon chain length is unchanged.\n• Option (D): Incorrect. Dehydration gives ethene, not ethanoic acid.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 12000),
    ),
    Question(
      id: "sci_ch4_p71_q02",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 71)] A mixture of ethyne and oxygen is burnt for welding metals. Why is a mixture of ethyne and ordinary air NOT used?",
      options: const [
        QuestionOption(id: "A", text: "Ethyne has a high carbon percentage (\$92.3\\%\$); in air (only \$\\sim 21\\%\\ \\text{O}_2\$), it undergoes incomplete combustion giving a sooty yellow flame with insufficient temperature, whereas pure \$\\text{O}_2\$ gives complete combustion with an oxy-acetylene flame exceeding 3000°C.", isCorrect: true),
        QuestionOption(id: "B", text: "Air contains carbon dioxide which reacts with ethyne to form explosive cyanides.", isCorrect: false),
        QuestionOption(id: "C", text: "Ethyne does not ignite or catch fire in air under any circumstances.", isCorrect: false),
        QuestionOption(id: "D", text: "Pure oxygen acts as a chemical flux that dissolves the iron slag directly.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Ethyne has a high carbon percentage (\$92.3\\%\$); in air (only \$\\\\sim 21\\%\\ \\text{O}_2\$), it undergoes incomplete combustion giving a sooty yellow flame with insufficient temperature, whereas pure \$\\text{O}_2\$ gives complete combustion with an oxy-acetylene flame exceeding 3000°C.\n\nScientific Principle / Key Concept:\n• Ethyne (acetylene, \$\\text{C}_2\\text{H}_2\$) is an unsaturated alkyne with a very high carbon-to-hydrogen ratio (\$92.3\\%\$ carbon by mass).\n• When burnt in air, the limited oxygen supply (\$\\\\sim 21\\%\$) leads to incomplete combustion, producing unburnt carbon particles (soot) and a flame temperature of only about 2000°C, which is insufficient to melt metals for welding.\n• When burnt with pure oxygen (oxy-acetylene flame), complete combustion takes place:\n\$\$2\\text{C}_2\\text{H}_2 + 5\\text{O}_2 \\rightarrow 4\\text{CO}_2 + 2\\text{H}_2\\text{O} + \\text{Heat}\$\$\nThis produces a non-sooty, clean blue flame reaching temperatures above 3000°C, ideal for cutting and welding metals.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Cyanides are not produced.\n• Option (C): Incorrect. Ethyne burns in air, but incompletely.\n• Option (D): Incorrect. Oxygen is the reactant oxidizer, not a metallurgical flux.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 13000),
    ),
    Question(
      id: "sci_ch4_p74_q01",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 74)] How can you distinguish experimentally between an alcohol (e.g., ethanol) and a carboxylic acid (e.g., ethanoic acid)?",
      options: const [
        QuestionOption(id: "A", text: "Add sodium hydrogen carbonate (\$\\text{NaHCO}_3\$): ethanoic acid produces brisk effervescence of \$\\text{CO}_2\$ gas (turning lime water milky), while ethanol gives no reaction.", isCorrect: true),
        QuestionOption(id: "B", text: "Dip blue litmus paper: ethanol turns blue litmus red, whereas ethanoic acid has no effect on litmus.", isCorrect: false),
        QuestionOption(id: "C", text: "Add water: ethanol is completely insoluble, while ethanoic acid dissolves with a violent explosion.", isCorrect: false),
        QuestionOption(id: "D", text: "Heat with copper: ethanol forms metallic gold while ethanoic acid precipitates solid carbon.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Add sodium hydrogen carbonate (\$\\text{NaHCO}_3\$): ethanoic acid produces brisk effervescence of \$\\text{CO}_2\$ gas (turning lime water milky), while ethanol gives no reaction.\n\nScientific Principle / Key Concept:\n1. Sodium hydrogen carbonate test:\n\$\$\\text{CH}_3\\text{COOH} + \\text{NaHCO}_3 \\rightarrow \\text{CH}_3\\text{COONa} + \\text{H}_2\\text{O} + \\text{CO}_2\\uparrow\$\$\nEthanoic acid releases \$\\text{CO}_2\$ gas which produces brisk effervescence and turns freshly prepared lime water milky. Ethanol does not react with \$\\text{NaHCO}_3\$.\n2. Litmus test:\nEthanoic acid turns blue litmus paper red, while ethanol is neutral and does not affect litmus paper.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Ethanoic acid is acidic (turns blue litmus red); ethanol is neutral.\n• Option (C): Incorrect. Both are completely water-soluble.\n• Option (D): Incorrect. Chemically impossible transmutation.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 14000),
    ),
    Question(
      id: "sci_ch4_p74_q02",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 74)] What are oxidising agents, and which of the following are examples used to oxidise alcohols to carboxylic acids?",
      options: const [
        QuestionOption(id: "A", text: "Substances capable of adding oxygen to or removing hydrogen/electrons from other reactants; examples include alkaline \$\\text{KMnO}_4\$ and acidified \$\\text{K}_2\\text{Cr}_2\\text{O}_7\$.", isCorrect: true),
        QuestionOption(id: "B", text: "Substances that remove oxygen from compounds; examples include hot concentrated sulphuric acid.", isCorrect: false),
        QuestionOption(id: "C", text: "Substances that add hydrogen to double bonds; examples include nickel and palladium catalysts.", isCorrect: false),
        QuestionOption(id: "D", text: "Substances that dissolve salts without altering chemical structure; examples include liquid water.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Substances capable of adding oxygen to or removing hydrogen/electrons from other reactants; examples include alkaline \$\\text{KMnO}_4\$ and acidified \$\\text{K}_2\\text{Cr}_2\\text{O}_7\$.\n\nScientific Principle / Key Concept:\nSome substances are capable of adding oxygen to others; these substances are known as oxidising agents. In the context of organic chemistry:\n• Alkaline potassium permanganate (\$\\text{KMnO}_4 + \\text{NaOH}\$)\n• Acidified potassium dichromate (\$\\text{K}_2\\text{Cr}_2\\text{O}_7 + \\text{H}_2\\text{SO}_4\$)\nBoth act as powerful oxidising agents that convert alcohols into carboxylic acids upon heating.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Removing oxygen is the role of reducing agents.\n• Option (C): Incorrect. Hydrogenation catalysts cause reduction.\n• Option (D): Incorrect. Solvents do not drive oxidation.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 15000),
    ),
    Question(
      id: "sci_ch4_p76_q01",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 76)] Would you be able to check if water is hard by using a synthetic detergent?",
      options: const [
        QuestionOption(id: "A", text: "No, because synthetic detergents form rich lather equally in both soft and hard water without forming insoluble scum precipitates with \$\\text{Ca}^{2+}\$ and \$\\text{Mg}^{2+}\$ ions.", isCorrect: true),
        QuestionOption(id: "B", text: "Yes, because detergents turn hard water into a thick yellow gelatinous curd.", isCorrect: false),
        QuestionOption(id: "C", text: "Yes, because detergents lose their cleansing properties and decompose completely in hard water.", isCorrect: false),
        QuestionOption(id: "D", text: "Yes, because detergents precipitate calcium ions as metallic limestone rocks.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) No, because synthetic detergents form rich lather equally in both soft and hard water without forming insoluble scum precipitates with \$\\text{Ca}^{2+}\$ and \$\\text{Mg}^{2+}\$ ions.\n\nScientific Principle / Key Concept:\n• Hardness in water is caused by dissolved hydrogencarbonates, chlorides, or sulphates of calcium and magnesium.\n• Soaps react with \$\\text{Ca}^{2+}\$ and \$\\text{Mg}^{2+}\$ to form an insoluble white curdy precipitate called scum, failing to lather until all hardness ions are precipitated.\n• Detergents are sodium salts of alkylbenzenesulphonates or ammonium salts. The charged ends of these molecules do not form insoluble precipitates with \$\\text{Ca}^{2+}\$ and \$\\text{Mg}^{2+}\$.\n• Because detergents produce foam/lather readily in both soft and hard water, they cannot be used to distinguish hard water from soft water.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Soap forms scum, not detergent.\n• Option (C): Incorrect. Detergents work effectively in hard water.\n• Option (D): Incorrect. Detergents keep ions in solution.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 16000),
    ),
    Question(
      id: "sci_ch4_p76_q02",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[QUESTIONS (Page 76)] Why is mechanical agitation (beating on a stone, paddle, scrubbing with brush, or tumbling in a washing machine) necessary to get clean clothes with soap?",
      options: const [
        QuestionOption(id: "A", text: "Soap micelles entrap oily dirt at their hydrophobic centers, but mechanical agitation is needed to physically detach and pull these loaded micelles away from fabric fibers into the water emulsion.", isCorrect: true),
        QuestionOption(id: "B", text: "Agitation heats the water above 100°C causing the oil molecules to evaporate instantly.", isCorrect: false),
        QuestionOption(id: "C", text: "Agitation breaks the covalent bonds of soap molecules into atomic sodium metal.", isCorrect: false),
        QuestionOption(id: "D", text: "Beating clothes turns soap from an acidic substance into an alkaline detergent.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Soap micelles entrap oily dirt at their hydrophobic centers, but mechanical agitation is needed to physically detach and pull these loaded micelles away from fabric fibers into the water emulsion.\n\nScientific Principle / Key Concept:\n• Dirt on clothes is predominantly oily or greasy in nature.\n• Soap molecules orient themselves into spherical micelles, where the non-polar hydrophobic tails dissolve in the oil droplet, and the polar ionic heads project outwards into the water.\n• The micelles hold the oily dirt in colloidal suspension, but surface adhesion keeps them clinging to fabric threads.\n• Mechanical agitation (scrubbing, beating, or spinning in a machine) overcomes this surface attraction, dislodging the micelles with their entrapped dirt into the bulk water, allowing them to be washed away during rinsing.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Agitation does not boil water.\n• Option (C): Incorrect. Covalent bonds are not broken by mechanical paddles.\n• Option (D): Incorrect. Mechanical force does not change chemical pH.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 17000),
    ),
    Question(
      id: "sci_ch4_ex_q01",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 1] Ethane, with the molecular formula \$\\text{C}_2\\text{H}_6\$, has:",
      options: const [
        QuestionOption(id: "A", text: "7 covalent bonds.", isCorrect: true),
        QuestionOption(id: "B", text: "6 covalent bonds.", isCorrect: false),
        QuestionOption(id: "C", text: "8 covalent bonds.", isCorrect: false),
        QuestionOption(id: "D", text: "9 covalent bonds.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) 7 covalent bonds.\n\nScientific Principle / Key Concept:\n• The structural formula of ethane is \$\\text{H}_3\\text{C}-\\text{CH}_3\$.\n• Count of bonds:\n  - One C-C single covalent bond = 1\n  - Six C-H single covalent bonds = 6\n  - Total covalent bonds = \$1 + 6 = 7\$.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Forgets the C-C bond.\n• Option (C): Incorrect. Exceeds octet requirement.\n• Option (D): Incorrect. Arithmetically impossible for \$\\text{C}_2\\text{H}_6\$.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 18000),
    ),
    Question(
      id: "sci_ch4_ex_q02",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 2] Butanone is a four-carbon compound with the functional group:",
      options: const [
        QuestionOption(id: "A", text: "Ketone.", isCorrect: true),
        QuestionOption(id: "B", text: "Carboxylic acid.", isCorrect: false),
        QuestionOption(id: "C", text: "Aldehyde.", isCorrect: false),
        QuestionOption(id: "D", text: "Alcohol.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Ketone.\n\nScientific Principle / Key Concept:\n• The name 'Butanone' has root word 'but-' (4 carbons) and suffix '-one'.\n• The suffix '-one' is the characteristic IUPAC suffix for a ketone (\$>\\text{C}=\\text{O}\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Carboxylic acid suffix is '-oic acid'.\n• Option (C): Incorrect. Aldehyde suffix is '-al'.\n• Option (D): Incorrect. Alcohol suffix is '-ol'.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 19000),
    ),
    Question(
      id: "sci_ch4_ex_q03",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 3] While cooking, if the bottom of the vessel is getting blackened on the outside, it means that:",
      options: const [
        QuestionOption(id: "A", text: "The fuel is not burning completely.", isCorrect: true),
        QuestionOption(id: "B", text: "The food is not cooked completely.", isCorrect: false),
        QuestionOption(id: "C", text: "The fuel is wet.", isCorrect: false),
        QuestionOption(id: "D", text: "The fuel is burning completely.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The fuel is not burning completely.\n\nScientific Principle / Key Concept:\n• Complete combustion of hydrocarbon fuels produces carbon dioxide, water vapor, and a non-luminous clean blue flame with no residue.\n• When air inlets are blocked or oxygen supply is limited, incomplete combustion occurs. Unburnt carbon particles glow yellow (giving a luminous flame) and deposit on the cold bottom of cooking vessels as black soot.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Blackening is external flame soot.\n• Option (C): Incorrect. Wet fuel is not the direct chemical explanation.\n• Option (D): Incorrect. Complete combustion yields a clean non-sooty flame.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 20000),
    ),
    Question(
      id: "sci_ch4_ex_q04",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 4] Explain the nature of covalent bonding using the bond formation in chloromethane (\$\\text{CH}_3\\text{Cl}\$).",
      options: const [
        QuestionOption(id: "A", text: "Carbon forms three non-polar single covalent bonds with three hydrogen atoms and one polar single covalent bond with chlorine due to chlorine's higher electronegativity, with all atoms completing their octets/duplets by sharing electron pairs.", isCorrect: true),
        QuestionOption(id: "B", text: "Carbon loses an electron to chlorine to form an ionic bond while sharing three coordinate covalent bonds with hydrogen.", isCorrect: false),
        QuestionOption(id: "C", text: "Chlorine donates two lone pairs to carbon forming a double covalent bond.", isCorrect: false),
        QuestionOption(id: "D", text: "All four bonds in \$\\text{CH}_3\\text{Cl}\$ are completely non-polar with zero dipole moment.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Carbon forms three non-polar single covalent bonds with three hydrogen atoms and one polar single covalent bond with chlorine due to chlorine's higher electronegativity, with all atoms completing their octets/duplets by sharing electron pairs.\n\nScientific Principle / Key Concept:\n• Carbon (\$Z=6\$, configuration \$2,4\$) has 4 valence electrons.\n• Hydrogen (\$Z=1\$, configuration \$1\$) has 1 valence electron and needs 1 to achieve helium duplet.\n• Chlorine (\$Z=17\$, configuration \$2,8,7\$) has 7 valence electrons and needs 1 to complete its octet.\n• Carbon shares 1 electron with each of 3 hydrogen atoms (three C-H single covalent bonds) and 1 electron with the chlorine atom (one C-Cl single covalent bond).\n• Because chlorine is much more electronegative than carbon, it pulls the shared pair closer to itself, making the C-Cl bond polar covalent with partial charges (\$\\text{C}^{\\delta+}-\\text{Cl}^{\\delta-}\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. C-Cl is a polar covalent bond, not an electrovalent ionic lattice.\n• Option (C): Incorrect. Chlorine forms a single bond.\n• Option (D): Incorrect. The molecule has a significant dipole moment.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 21000),
    ),
    Question(
      id: "sci_ch4_ex_q05_a",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 5(a)] In the electron dot structure of ethanoic acid (\$\\text{CH}_3\\text{COOH}\$), how many total shared electron pairs (covalent bonds) and lone pairs of electrons are present?",
      options: const [
        QuestionOption(id: "A", text: "8 shared electron pairs (covalent bonds) and 4 unshared lone pairs of electrons (on the oxygen atoms).", isCorrect: true),
        QuestionOption(id: "B", text: "6 shared electron pairs and 2 lone pairs.", isCorrect: false),
        QuestionOption(id: "C", text: "10 shared electron pairs and 0 lone pairs.", isCorrect: false),
        QuestionOption(id: "D", text: "7 shared electron pairs and 6 lone pairs.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) 8 shared electron pairs (covalent bonds) and 4 unshared lone pairs of electrons (on the oxygen atoms).\n\nScientific Principle / Key Concept:\n• Total valence electrons in \$\\text{CH}_3\\text{COOH}\$ = \$2(\\text{C}) \\times 4 + 4(\\text{H}) \\times 1 + 2(\\text{O}) \\times 6 = 8 + 4 + 12 = 24\$ electrons.\n• Shared pairs (bonds):\n  - 3 C-H single bonds = 3 pairs\n  - 1 C-C single bond = 1 pair\n  - 1 C=O double bond = 2 pairs\n  - 1 C-O single bond = 1 pair\n  - 1 O-H single bond = 1 pair\n  - Total shared pairs = 8 (16 electrons).\n• Remaining electrons = \$24 - 16 = 8\$ electrons = 4 lone pairs (2 lone pairs on carbonyl oxygen, 2 lone pairs on hydroxyl oxygen).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Undercounts C=O and C-C bonds.\n• Option (C): Incorrect. Oxygen atoms retain lone pairs to complete octets.\n• Option (D): Counts C=O as single bond.",
      difficultyLevel: DifficultyLevel.hots,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 22000),
    ),
    Question(
      id: "sci_ch4_ex_q05_b",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 5(b)] In the electron dot structure of hydrogen sulphide (\$\\text{H}_2\\text{S}\$), what is the bonding arrangement around the central sulphur atom?",
      options: const [
        QuestionOption(id: "A", text: "The central sulphur atom shares two single covalent bonds with two hydrogen atoms and retains two unshared lone pairs of electrons: \$\\text{H}-\\ddot{\\text{S}}-\\text{H}\$.", isCorrect: true),
        QuestionOption(id: "B", text: "Sulphur forms a double covalent bond with both hydrogen atoms simultaneously.", isCorrect: false),
        QuestionOption(id: "C", text: "Sulphur transfers two electrons to two protons forming \$\\text{S}^{2+}\$ and \$2\\text{H}^-\$.", isCorrect: false),
        QuestionOption(id: "D", text: "Sulphur forms an octet using only single bonds with no lone pairs.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The central sulphur atom shares two single covalent bonds with two hydrogen atoms and retains two unshared lone pairs of electrons: \$\\text{H}-\\ddot{\\text{S}}-\\text{H}\$.\n\nScientific Principle / Key Concept:\n• Sulphur (\$Z=16\$, configuration \$2,8,6\$) has 6 valence electrons.\n• Hydrogen (\$Z=1\$, configuration \$1\$) needs 1 electron for a stable duplet.\n• In \$\\text{H}_2\\text{S}\$, sulphur shares 1 electron pair with each of the two hydrogen atoms, forming two single S-H covalent bonds.\n• The remaining 4 valence electrons on sulphur exist as two lone pairs, giving a bent molecular geometry analogous to water (\$\\text{H}_2\\text{O}\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Hydrogen cannot form double bonds.\n• Option (C): Incorrect. \$\\text{H}_2\\text{S}\$ is covalent.\n• Option (D): Incorrect. Sulphur has 2 lone pairs.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 23000),
    ),
    Question(
      id: "sci_ch4_ex_q05_c",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 5(c)] In the electron dot structure of propanone (\$\\text{CH}_3\\text{COCH}_3\$), what is the total number of single covalent bonds and double covalent bonds?",
      options: const [
        QuestionOption(id: "A", text: "9 single covalent bonds (6 C-H and 2 C-C) and 1 double covalent bond (C=O).", isCorrect: true),
        QuestionOption(id: "B", text: "6 single covalent bonds and 2 double covalent bonds.", isCorrect: false),
        QuestionOption(id: "C", text: "10 single covalent bonds and 0 double covalent bonds.", isCorrect: false),
        QuestionOption(id: "D", text: "4 single covalent bonds and 3 double covalent bonds.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) 8 single covalent bonds (6 C-H and 2 C-C) and 1 double covalent bond (C=O), making 9 covalent linkages in total.\n\nScientific Principle / Key Concept:\n• Formula of propanone: \$\\text{CH}_3-\\text{C}(=\\text{O})-\\text{CH}_3\$.\n• Count of bonds:\n  - 6 C-H single bonds (three on each terminal methyl group)\n  - 2 C-C single bonds (connecting C1 to C2, and C2 to C3)\n  - 1 C=O double bond (between carbonyl carbon C2 and oxygen atom)\n• Oxygen atom also has 2 unshared lone pairs.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect number of double bonds.\n• Option (C): Propanone has a double bond, not all single bonds.\n• Option (D): Incorrect distribution.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 24000),
    ),
    Question(
      id: "sci_ch4_ex_q05_d",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 5(d)] What is the electron dot structure and bonding in a diatomic fluorine molecule (\$\\text{F}_2\$)?",
      options: const [
        QuestionOption(id: "A", text: "Two fluorine atoms share one electron pair, forming a single covalent bond (\$:\\ddot{\\text{F}}-\\ddot{\\text{F}}:\$), with each fluorine retaining 3 unshared lone pairs.", isCorrect: true),
        QuestionOption(id: "B", text: "Two fluorine atoms share two electron pairs, forming a double bond (\$\\text{F}=\\text{F}\$).", isCorrect: false),
        QuestionOption(id: "C", text: "One fluorine atom transfers an electron completely to the other, forming \$\\text{F}^+\$ and \$\\text{F}^-\$.", isCorrect: false),
        QuestionOption(id: "D", text: "Two fluorine atoms share three electron pairs to form a stable triple bond (\$\\text{F}\\equiv\\text{F}\$).", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Two fluorine atoms share one electron pair, forming a single covalent bond (\$:\\ddot{\\text{F}}-\\ddot{\\text{F}}:\$), with each fluorine retaining 3 unshared lone pairs.\n\nScientific Principle / Key Concept:\n• Fluorine (\$Z=9\$, electronic configuration \$2,7\$) has 7 valence electrons.\n• Each fluorine atom needs 1 electron to attain the stable octet of neon (\$2,8\$).\n• Two fluorine atoms contribute 1 electron each to form a shared electron pair (a single covalent bond).\n• Total shared electrons = 2 (1 single bond); unshared electrons = 6 on each fluorine (3 lone pairs each).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Halogens form single bonds.\n• Option (C): Incorrect. Homonuclear diatomic halogens are purely covalent.\n• Option (D): Incorrect. Nitrogen forms triple bonds, not fluorine.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 25000),
    ),
    Question(
      id: "sci_ch4_ex_q06",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 6] What is a homologous series? Which of the following correctly defines its characteristics with an example?",
      options: const [
        QuestionOption(id: "A", text: "A series of carbon compounds having the same functional group and similar chemical properties, where successive members differ by a \$-\\text{CH}_2-\$ unit and \$14\\text{ u}\$ in molecular mass (e.g., Alkanes: \$\\text{CH}_4, \\text{C}_2\\text{H}_6, \\text{C}_3\\text{H}_8\$).", isCorrect: true),
        QuestionOption(id: "B", text: "A mixture of structural isomers having identical boiling points and identical molecular masses.", isCorrect: false),
        QuestionOption(id: "C", text: "A group of elements arranged in order of increasing atomic masses in triads of three.", isCorrect: false),
        QuestionOption(id: "D", text: "A series of compounds where every eighth member has properties identical to the first.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) A series of carbon compounds having the same functional group and similar chemical properties, where successive members differ by a \$-\\text{CH}_2-\$ unit and \$14\\text{ u}\$ in molecular mass (e.g., Alkanes: \$\\text{CH}_4, \\text{C}_2\\text{H}_6, \\text{C}_3\\text{H}_8\$).\n\nScientific Principle / Key Concept:\nA homologous series is a family of organic compounds that possess:\n1. The same functional group and general molecular formula (e.g., \$\\text{C}_n\\text{H}_{2n+2}\$ for alkanes, \$\\text{C}_n\\text{H}_{2n+1}\\text{OH}\$ for alcohols).\n2. Successive members differ from each other by a single methylene group (\$-\\text{CH}_2-\$) and by \$14\\text{ u}\$ in molecular mass.\n3. All members exhibit similar chemical properties.\n4. Gradation in physical properties (such as increasing melting points, boiling points, and densities) is observed as molecular mass increases.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. That defines structural isomerism.\n• Option (C): Incorrect. That defines Döbereiner's triads.\n• Option (D): Incorrect. That defines Newlands' Law of Octaves.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 26000),
    ),
    Question(
      id: "sci_ch4_ex_q07",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 7] How can ethanol and ethanoic acid be differentiated on the basis of their physical and chemical properties?",
      options: const [
        QuestionOption(id: "A", text: "Physical: ethanol has a pleasant alcoholic odor and remains liquid in winter (MP \$156\\text{ K}\$), whereas ethanoic acid smells like pungent vinegar and freezes at \$290\\text{ K}\$ (glacial acetic acid). Chemical: ethanoic acid produces brisk effervescence of \$\\text{CO}_2\$ with \$\\text{NaHCO}_3\$ and turns blue litmus red, whereas ethanol gives no reaction.", isCorrect: true),
        QuestionOption(id: "B", text: "Physical: ethanol is a green solid while ethanoic acid is a purple gas. Chemical: ethanol turns red litmus blue while ethanoic acid has no effect.", isCorrect: false),
        QuestionOption(id: "C", text: "Physical: ethanol freezes at room temperature while ethanoic acid boils at 20°C. Chemical: both react identically with sodium bicarbonate.", isCorrect: false),
        QuestionOption(id: "D", text: "Physical: they have identical boiling points. Chemical: ethanol is an acid and ethanoic acid is an alkaline base.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Physical: ethanol has a pleasant alcoholic odor and remains liquid in winter (MP \$156\\text{ K}\$), whereas ethanoic acid smells like pungent vinegar and freezes at \$290\\text{ K}\$ (glacial acetic acid). Chemical: ethanoic acid produces brisk effervescence of \$\\text{CO}_2\$ with \$\\text{NaHCO}_3\$ and turns blue litmus red, whereas ethanol gives no reaction.\n\nScientific Principle / Key Concept:\n1. Physical Differences:\n• Odour: Ethanol has a characteristic pleasant alcoholic smell; ethanoic acid has a sharp pungent vinegar smell.\n• Melting Point: Ethanol has MP = 156 K (-117°C). Ethanoic acid has MP = 290 K (17°C), so it frequently freezes during winter in cold climates (hence called glacial acetic acid).\n2. Chemical Differences:\n• Reaction with \$\\text{NaHCO}_3\$: Ethanoic acid reacts vigorously with sodium hydrogen carbonate liberating \$\\text{CO}_2\$ gas with brisk effervescence: \$\\text{CH}_3\\text{COOH} + \\text{NaHCO}_3 \\rightarrow \\text{CH}_3\\text{COONa} + \\text{H}_2\\text{O} + \\text{CO}_2\\uparrow\$. Ethanol shows no reaction.\n• Litmus Test: Ethanoic acid turns blue litmus red; ethanol is neutral and does not change litmus color.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect colors and litmus states.\n• Option (C): Reverses freezing characteristics.\n• Option (D): Ethanol is not an acid and ethanoic acid is not a base.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 27000),
    ),
    Question(
      id: "sci_ch4_ex_q08",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 8] Why does micelle formation take place when soap is added to water? Will a micelle be formed in other solvents such as ethanol?",
      options: const [
        QuestionOption(id: "A", text: "Soap has a hydrophilic ionic head and a hydrophobic hydrocarbon tail; in water, the tails cluster together in the interior away from water, while the heads point outward. In ethanol, micelles do NOT form because the hydrocarbon tail dissolves directly in non-polar/organic ethanol.", isCorrect: true),
        QuestionOption(id: "B", text: "Micelles form in water because soap is insoluble; in ethanol, micelles form twice as fast and grow into crystalline diamonds.", isCorrect: false),
        QuestionOption(id: "C", text: "Micelle formation occurs identically in all liquid solvents regardless of polarity.", isCorrect: false),
        QuestionOption(id: "D", text: "Micelles form in water because sodium ions evaporate, whereas in ethanol sodium remains solid.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Soap has a hydrophilic ionic head and a hydrophobic hydrocarbon tail; in water, the tails cluster together in the interior away from water, while the heads point outward. In ethanol, micelles do NOT form because the hydrocarbon tail dissolves directly in non-polar/organic ethanol.\n\nScientific Principle / Key Concept:\n1. Why micelles form in water:\nSoap molecules have dual characteristics:\n• Ionic 'head' (\$\\text{COO}^-\\text{Na}^+\$): hydrophilic (water-attracting), soluble in water.\n• Hydrocarbon 'tail' (long alkyl chain): hydrophobic (water-repelling), insoluble in water.\nTo minimize contact between hydrocarbon tails and water, the molecules arrange radially into spherical clusters (micelles): the hydrophobic tails point inward towards the center, while the ionic heads project outward into the aqueous solvent.\n2. In ethanol:\nEthanol is an organic solvent with low dielectric constant compared to water. The hydrocarbon tail of soap is soluble in ethanol. Therefore, the driving force for hydrophobic aggregation is absent, and soap dissolves uniformly without forming micelles.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Diamonds are not formed and micelles do not occur in ethanol.\n• Option (C): Incorrect. Micellization requires solvent polarity asymmetry.\n• Option (D): Sodium ions do not evaporate.",
      difficultyLevel: DifficultyLevel.hots,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 28000),
    ),
    Question(
      id: "sci_ch4_ex_q09",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 9] Why are carbon and its compounds used as fuels for most applications?",
      options: const [
        QuestionOption(id: "A", text: "They possess high calorific value (release substantial heat energy per unit mass upon combustion), have optimum ignition temperatures, and undergo controlled combustion producing non-toxic gaseous products.", isCorrect: true),
        QuestionOption(id: "B", text: "They undergo spontaneous combustion at 0°C without requiring any spark or flame.", isCorrect: false),
        QuestionOption(id: "C", text: "They contain free uranium nuclei that release nuclear fission energy during burning.", isCorrect: false),
        QuestionOption(id: "D", text: "They do not react with oxygen and can only burn in pure nitrogen gas.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) They possess high calorific value (release substantial heat energy per unit mass upon combustion), have optimum ignition temperatures, and undergo controlled combustion producing non-toxic gaseous products.\n\nScientific Principle / Key Concept:\nCarbon and its compounds are predominantly used as domestic and industrial fuels because:\n1. High Calorific Value: On combustion, they release a large amount of heat and light energy per unit mass due to strong bond energies in products (\$\\text{CO}_2\$ and \$\\text{H}_2\\text{O}\$).\n2. Optimum Ignition Temperature: They ignite easily when heated but remain stable and safe to store at room temperature.\n3. Clean Burning: Saturated hydrocarbons burn with a clean, smoke-free flame and leave no solid residue or ash (for gases/liquids).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Low ignition temperatures cause storage hazards.\n• Option (C): Incorrect. Combustion is a chemical process, not nuclear.\n• Option (D): Incorrect. Combustion requires oxygen.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 29000),
    ),
    Question(
      id: "sci_ch4_ex_q10",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 10] Explain the chemical formation of scum when hard water is treated with soap.",
      options: const [
        QuestionOption(id: "A", text: "Soluble calcium (\$\\text{Ca}^{2+}\$) and magnesium (\$\\text{Mg}^{2+}\$) ions in hard water react with sodium soap molecules to form insoluble, curdy white precipitates of calcium and magnesium stearate/palmitate (scum).", isCorrect: true),
        QuestionOption(id: "B", text: "Hard water evaporates the soap molecules into toxic chlorine gas.", isCorrect: false),
        QuestionOption(id: "C", text: "Soap converts calcium carbonate into soluble carbon dioxide gas causing bubbles to pop.", isCorrect: false),
        QuestionOption(id: "D", text: "Scum is formed by sodium ions reacting with distilled pure water.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Soluble calcium (\$\\text{Ca}^{2+}\$) and magnesium (\$\\text{Mg}^{2+}\$) ions in hard water react with sodium soap molecules to form insoluble, curdy white precipitates of calcium and magnesium stearate/palmitate (scum).\n\nScientific Principle / Key Concept:\n• Hard water contains dissolved salts of calcium (\$\\text{Ca}^{2+}\$) and magnesium (\$\\text{Mg}^{2+}\$), such as \$\\text{CaCl}_2\$, \$\\text{MgSO}_4\$, \$\\text{Ca(HCO}_3)_2\$.\n• Soap is a sodium or potassium salt of long-chain fatty acids (e.g., sodium stearate \$\\text{C}_{17}\\text{H}_{35}\\text{COONa}\$).\n• When soap is added to hard water, double displacement takes place:\n\$\$2\\text{C}_{17}\\text{H}_{35}\\text{COONa}(aq) + \\text{Ca}^{2+}(aq) \\rightarrow (\\text{C}_{17}\\text{H}_{35}\\text{COO})_2\\text{Ca}\\downarrow\\text{ (Insoluble Scum)} + 2\\text{Na}^+(aq)\$\$\nThis insoluble precipitate floats as scum and wastes soap until all \$\\text{Ca}^{2+}\$ and \$\\text{Mg}^{2+}\$ ions are consumed.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. No chlorine is involved.\n• Option (C): Incorrect. Scum is an insoluble solid, not a gas.\n• Option (D): Incorrect. Pure distilled water lathers instantly with no scum.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 30000),
    ),
    Question(
      id: "sci_ch4_ex_q11",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 11] What change will you observe if you test an aqueous soap solution with red and blue litmus paper?",
      options: const [
        QuestionOption(id: "A", text: "Red litmus paper turns blue; blue litmus paper remains unchanged (blue).", isCorrect: true),
        QuestionOption(id: "B", text: "Blue litmus paper turns red; red litmus paper remains unchanged (red).", isCorrect: false),
        QuestionOption(id: "C", text: "Both red and blue litmus papers are bleached completely white.", isCorrect: false),
        QuestionOption(id: "D", text: "Neither litmus paper undergoes any change in color because soap is chemically neutral.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Red litmus paper turns blue; blue litmus paper remains unchanged (blue).\n\nScientific Principle / Key Concept:\n• Soap is the salt of a weak organic acid (fatty acid like stearic acid) and a strong base (sodium hydroxide \$\\text{NaOH}\$).\n• When dissolved in water, soap hydrolyzes:\n\$\$\\text{RCOO}^-\\text{Na}^+ + \\text{H}_2\\text{O} \\rightleftharpoons \\text{RCOOH} + \\text{Na}^+ + \\text{OH}^-\$\$\n• The excess of hydroxide ions (\$\\text{OH}^-\$) makes the soap solution alkaline (basic).\n• Consequently, red litmus paper turns blue, while blue litmus paper remains blue.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Soap is basic, not acidic.\n• Option (C): Incorrect. Soap does not act as a bleaching agent.\n• Option (D): Incorrect. Salt of weak acid and strong base is distinctly basic.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 31000),
    ),
    Question(
      id: "sci_ch4_ex_q12",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 12] What is hydrogenation, and what is its major industrial application?",
      options: const [
        QuestionOption(id: "A", text: "Addition of hydrogen to unsaturated hydrocarbons in the presence of a nickel (\$\\text{Ni}\$) or palladium catalyst to form saturated hydrocarbons; industrial application is converting liquid vegetable oils into solid vegetable ghee (vanaspati).", isCorrect: true),
        QuestionOption(id: "B", text: "Removal of hydrogen from alkanes to form alkenes for plastics manufacturing.", isCorrect: false),
        QuestionOption(id: "C", text: "Reaction of hydrogen with atmospheric nitrogen to synthesize ammonia fertilizer.", isCorrect: false),
        QuestionOption(id: "D", text: "Splitting of water molecules into hydrogen and oxygen by electrolysis.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Addition of hydrogen to unsaturated hydrocarbons in the presence of a nickel (\$\\text{Ni}\$) or palladium catalyst to form saturated hydrocarbons; industrial application is converting liquid vegetable oils into solid vegetable ghee (vanaspati).\n\nScientific Principle / Key Concept:\n• Definition: Hydrogenation is the chemical addition of hydrogen (\$\\text{H}_2\$) to unsaturated carbon compounds (containing double or triple bonds) in the presence of finely divided catalysts such as nickel (\$\\text{Ni}\$), palladium (\$\\text{Pd}\$), or platinum (\$\\text{Pt}\$):\n\$\$\\text{R}_2\\text{C}=\\text{CR}_2 + \\text{H}_2 \\xrightarrow{\\text{Ni, } 473\\text{ K}} \\text{R}_2\\text{CH}-\\text{CHR}_2\$\$\n• Industrial Application: Vegetable oils contain long unsaturated carbon chains and are liquids at room temperature. Hydrogenation converts these liquid unsaturated vegetable oils into solid saturated fats known as vegetable ghee (vanaspati ghee).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Removing hydrogen is dehydrogenation.\n• Option (C): Incorrect. That is the Haber process.\n• Option (D): Incorrect. That is electrolysis of water.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 32000),
    ),
    Question(
      id: "sci_ch4_ex_q13",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 13] Which of the following hydrocarbons undergo addition reactions: \$\\text{C}_2\\text{H}_6, \\text{C}_3\\text{H}_8, \\text{C}_3\\text{H}_6, \\text{C}_2\\text{H}_2, \\text{and }\\text{CH}_4\$?",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{C}_3\\text{H}_6\$ (propene) and \$\\text{C}_2\\text{H}_2\$ (ethyne)", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{C}_2\\text{H}_6\$, \$\\text{C}_3\\text{H}_8\$, and \$\\text{CH}_4\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{CH}_4\$ and \$\\text{C}_2\\text{H}_6\$ only", isCorrect: false),
        QuestionOption(id: "D", text: "All five hydrocarbons undergo addition reactions equally under sunlight.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{C}_3\\text{H}_6\$ (propene) and \$\\text{C}_2\\text{H}_2\$ (ethyne)\n\nScientific Principle / Key Concept:\n• Addition reactions are characteristic of unsaturated hydrocarbons (alkenes and alkynes) containing double or triple bonds between carbon atoms.\n1. \$\\text{C}_3\\text{H}_6\$ corresponds to \$\\text{C}_n\\text{H}_{2n}\$ (\$n=3\$) \$\\rightarrow\$ Propene (alkene, contains \$\\text{C}=\\text{C}\$ double bond). Undergoes addition!\n2. \$\\text{C}_2\\text{H}_2\$ corresponds to \$\\text{C}_n\\text{H}_{2n-2}\$ (\$n=2\$) \$\\rightarrow\$ Ethyne (alkyne, contains \$\\text{C}\\equiv\\text{C}\$ triple bond). Undergoes addition!\n3. \$\\text{CH}_4, \\text{C}_2\\text{H}_6, \\text{C}_3\\text{H}_8\$ correspond to \$\\text{C}_n\\text{H}_{2n+2}\$ \$\\rightarrow\$ Saturated alkanes with single bonds only. They undergo substitution reactions, NOT addition reactions.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Saturated alkanes do not undergo addition.\n• Option (C): Methane and ethane have single bonds only.\n• Option (D): Misidentifies substitution as addition.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 33000),
    ),
    Question(
      id: "sci_ch4_ex_q14",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 14] Which chemical test can be used to differentiate clearly between butter and cooking oil?",
      options: const [
        QuestionOption(id: "A", text: "Bromine water test (or alkaline \$\\text{KMnO}_4\$ test): cooking oil contains unsaturated fatty acids and decolorizes reddish-brown bromine water, while butter contains saturated fats and does not decolorize bromine water.", isCorrect: true),
        QuestionOption(id: "B", text: "Litmus test: cooking oil turns blue litmus red while butter turns red litmus blue.", isCorrect: false),
        QuestionOption(id: "C", text: "Reaction with hydrochloric acid: butter dissolves completely with hydrogen effervescence while cooking oil forms copper sulphate.", isCorrect: false),
        QuestionOption(id: "D", text: "Electrical conductivity test: butter conducts electricity with zero resistance while cooking oil explodes.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Bromine water test (or alkaline \$\\text{KMnO}_4\$ test): cooking oil contains unsaturated fatty acids and decolorizes reddish-brown bromine water, while butter contains saturated fats and does not decolorize bromine water.\n\nScientific Principle / Key Concept:\n• Cooking oil is a vegetable oil containing unsaturated fatty acids with double bonds (\$\\text{C}=\\text{C}\$).\n• Butter is an animal fat containing saturated fatty acids with single bonds only.\n• Test with Bromine Water:\n  - Add a few drops of reddish-brown bromine water to cooking oil: The bromine adds across the double bonds (addition reaction), causing the reddish-brown color to disappear (decolorization).\n  - Add bromine water to melted butter: Saturated fats do not undergo addition reactions; the reddish-brown color of bromine water persists.\n• Alternatively, alkaline \$\\text{KMnO}_4\$ (Baeyer's reagent) is decolorized by cooking oil, but not by butter.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Both are neutral lipids.\n• Option (C): Incorrect. Fats do not release \$\\text{H}_2\$ with acid.\n• Option (D): Incorrect. Both are electrical insulators.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 34000),
    ),
    Question(
      id: "sci_ch4_ex_q15",
      subject: Subject.science,
      chapterId: "sci_ch_04_carbon_compounds",
      questionText: "[NCERT Exercise 15] Which statement correctly explains the step-by-step mechanism of the cleansing action of soaps?",
      options: const [
        QuestionOption(id: "A", text: "The hydrophobic hydrocarbon tails dissolve in the central oily dirt droplet, while the hydrophilic ionic heads face outward into water forming a micelle; mutual ionic repulsion prevents aggregation, keeping the emulsified dirt suspended in water until rinsed away.", isCorrect: true),
        QuestionOption(id: "B", text: "Soap molecules chemically convert insoluble oil dirt into volatile methane gas which evaporates immediately into air.", isCorrect: false),
        QuestionOption(id: "C", text: "Soap dissolves the cotton fabric fibers so that dirt drops out into the laundry tub.", isCorrect: false),
        QuestionOption(id: "D", text: "Hydrophilic tails dissolve in oil while hydrophobic heads dissolve in water.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The hydrophobic hydrocarbon tails dissolve in the central oily dirt droplet, while the hydrophilic ionic heads face outward into water forming a micelle; mutual ionic repulsion prevents aggregation, keeping the emulsified dirt suspended in water until rinsed away.\n\nScientific Principle / Key Concept:\nMechanism of Soap Cleansing Action:\n1. Oily dirt is insoluble in water.\n2. Soap molecules have two ends:\n   • Non-polar hydrocarbon tail: hydrophobic (water-hating) and lipophilic (oil-loving).\n   • Polar ionic head (\$-\\text{COO}^-\\text{Na}^+\$): hydrophilic (water-loving).\n3. When soap is added to dirty clothes in water, the hydrophobic tails embed themselves into the oily dirt droplet, while the hydrophilic ionic heads project outward into the surrounding water.\n4. This forms a spherical structure called a micelle, trapping the oil droplet inside.\n5. Because all micelle surfaces carry like negative charges (\$\\text{COO}^-\$), they repel one another (ion-ion repulsion) and do not precipitate or coalesce.\n6. With mechanical agitation and rinsing, the stable emulsion of dirt-loaded micelles is washed away, leaving the fabric clean.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Oil is emulsified, not converted to gas.\n• Option (C): Incorrect. Fabric is preserved, not dissolved.\n• Option (D): Inverts tail and head affinities.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 35000),
    ),
  ];
}
