import '../models/question.dart';

/// Pre-seeded NCERT-verified questions for NcertScienceCh2Data
class NcertScienceCh2Data {
  static List<Question> get questions => [
    Question(
      id: "sci_ch2_p18_q01",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 18)] You are given three test tubes containing distilled water, acidic solution, and basic solution respectively, and only red litmus paper. How can you identify the contents of each test tube?",
      options: const [
        QuestionOption(id: "A", text: "Dip red litmus into each; the one turning it blue is basic. Dip that blue litmus into the remaining two; the one turning it red is acidic, and the last is distilled water.", isCorrect: true),
        QuestionOption(id: "B", text: "Dip red litmus into each; the one turning it colorless is acidic, the one turning it blue is distilled water, and the one turning it red is basic.", isCorrect: false),
        QuestionOption(id: "C", text: "Red litmus will turn blue in both distilled water and basic solution, but remain unchanged in acidic solution.", isCorrect: false),
        QuestionOption(id: "D", text: "Dip red litmus into each; acidic solution turns it green, basic solution turns it red, and distilled water turns it yellow.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Dip red litmus into each; the one turning it blue is basic. Dip that blue litmus into the remaining two; the one turning it red is acidic, and the last is distilled water.\n\nScientific Principle / Key Concept:\nRed litmus turns blue strictly in basic medium. Once turned blue, it functions as blue litmus to identify the acid (which turns it back to red), leaving neutral distilled water unchanged.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Litmus does not bleach to colorless in standard dilute acids, and neutral distilled water does not turn red litmus blue.\n• Option (C): Incorrect. Distilled water is chemically neutral (pH ≈ 7) and does not turn red litmus blue.\n• Option (D): Incorrect. Litmus has only red and blue color states; green and yellow correspond to universal indicator, not litmus.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 0),
    ),
    Question(
      id: "sci_ch2_p22_q01",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 22)] Why should curd and sour substances not be kept in brass and copper vessels?",
      options: const [
        QuestionOption(id: "A", text: "Curd contains lactic acid which reacts with brass and copper forming toxic, poisonous metal salts.", isCorrect: true),
        QuestionOption(id: "B", text: "Brass and copper metals absorb the natural fat and moisture from curd, causing the curd to dry out.", isCorrect: false),
        QuestionOption(id: "C", text: "Curd neutralizes copper to produce insoluble inert copper metal granules that solidify the food.", isCorrect: false),
        QuestionOption(id: "D", text: "Brass and copper act as refrigerants that lower the temperature of curd and freeze its microbial cultures.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Curd contains lactic acid which reacts with brass and copper forming toxic, poisonous metal salts.\n\nScientific Principle / Key Concept:\nSour food substances contain organic acids (like lactic acid) that corrode copper and zinc in brass, producing soluble toxic metallic salts that can cause severe food poisoning.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. The hazard is a chemical reaction forming toxic salts, not physical fat absorption.\n• Option (C): Incorrect. Acids do not reduce copper; they react with metallic oxides and copper to yield poisonous soluble copper compounds.\n• Option (D): Incorrect. Brass and copper are normal conductors of heat and do not have chemical refrigerating properties.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 1000),
    ),
    Question(
      id: "sci_ch2_p22_q02",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 22)] Which gas is usually liberated when an acid reacts with a metal, and how is its presence confirmed?",
      options: const [
        QuestionOption(id: "A", text: "Hydrogen gas (\$\\text{H}_2\$); confirmed because it burns with a characteristic 'pop' sound when a burning splinter is brought near.", isCorrect: true),
        QuestionOption(id: "B", text: "Oxygen gas (\$\\text{O}_2\$); confirmed because it rekindles a glowing wooden splinter.", isCorrect: false),
        QuestionOption(id: "C", text: "Carbon dioxide (\$\\text{CO}_2\$); confirmed because it turns clear lime water milky.", isCorrect: false),
        QuestionOption(id: "D", text: "Chlorine gas (\$\\text{Cl}_2\$); confirmed by its pungent choking odor and bleaching of moist litmus paper.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Hydrogen gas (\$\\text{H}_2\$); confirmed because it burns with a characteristic 'pop' sound when a burning splinter is brought near.\n\nScientific Principle / Key Concept:\nActive metals displace hydrogen from dilute acids: \$\\text{Zn} + \\text{H}_2\\text{SO}_4 \\rightarrow \\text{ZnSO}_4 + \\text{H}_2\\uparrow\$. Hydrogen gas burns explosively in air with a distinctive 'pop' sound.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Acids reacting with metals yield hydrogen, not oxygen.\n• Option (C): Incorrect. \$\\text{CO}_2\$ is evolved when acids react with carbonates or hydrogencarbonates, not pure metals.\n• Option (D): Incorrect. \$\\text{Cl}_2\$ is not the standard gas liberated in simple acid-metal displacement reactions.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 2000),
    ),
    Question(
      id: "sci_ch2_p22_q03",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 22)] Metal compound 'A' reacts with dilute \$\\text{HCl}\$ to produce effervescence. The gas evolved extinguishes a burning candle. Write the balanced equation if one product is \$\\text{CaCl}_2\$.",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{CaCO}_3(s) + 2\\text{HCl}(aq) \\rightarrow \\text{CaCl}_2(aq) + \\text{H}_2\\text{O}(l) + \\text{CO}_2(g)\$", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{CaO}(s) + 2\\text{HCl}(aq) \\rightarrow \\text{CaCl}_2(aq) + \\text{H}_2\\text{O}(l)\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{Ca}(s) + 2\\text{HCl}(aq) \\rightarrow \\text{CaCl}_2(aq) + \\text{H}_2(g)\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{Ca(OH)}_2(aq) + 2\\text{HCl}(aq) \\rightarrow \\text{CaCl}_2(aq) + 2\\text{H}_2\\text{O}(l)\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{CaCO}_3(s) + 2\\text{HCl}(aq) \\rightarrow \\text{CaCl}_2(aq) + \\text{H}_2\\text{O}(l) + \\text{CO}_2(g)\$\n\nScientific Principle / Key Concept:\nCompound A is calcium carbonate (\$\\text{CaCO}_3\$). Effervescence is caused by \$\\text{CO}_2\$ gas, which does not support combustion and extinguishes candles.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Reaction with calcium oxide does not evolve gas effervescence.\n• Option (C): Incorrect. Elemental calcium is a metal, not a metal compound, and \$\\text{H}_2\$ gas burns with a pop rather than extinguishing flame without burning.\n• Option (D): Incorrect. Neutralisation of slaked lime does not produce gas effervescence.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 3000),
    ),
    Question(
      id: "sci_ch2_p28_q01",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 28)] Why do aqueous solutions of \$\\text{HCl}\$ and \$\\text{HNO}_3\$ show acidic character, whereas solutions of compounds like alcohol and glucose do not?",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{HCl}\$ and \$\\text{HNO}_3\$ dissociate in water to produce free \$\\text{H}^+(aq)\$ (hydronium) ions, whereas glucose and alcohol do not ionize.", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{HCl}\$ and \$\\text{HNO}_3\$ contain oxygen atoms while glucose and alcohol do not contain any oxygen.", isCorrect: false),
        QuestionOption(id: "C", text: "Glucose and alcohol react with water to form strongly basic hydroxide ions that suppress acidity.", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{HCl}\$ and \$\\text{HNO}_3\$ evaporate instantly in water, leaving solid hydrogen ions behind.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{HCl}\$ and \$\\text{HNO}_3\$ dissociate in water to produce free \$\\text{H}^+(aq)\$ (hydronium) ions, whereas glucose and alcohol do not ionize.\n\nScientific Principle / Key Concept:\nAcidic behavior depends strictly on the release of \$\\text{H}^+(aq) / \\text{H}_3\\text{O}^+\$ ions in aqueous solution. Covalent compounds like alcohol and glucose do not ionize.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Glucose (\$\\text{C}_6\\text{H}_{12}\\text{O}_6\$) and alcohol (\$\\text{C}_2\\text{H}_5\\text{OH}\$) both contain oxygen; oxygen content does not dictate acidity.\n• Option (C): Incorrect. Glucose and alcohol do not generate hydroxide ions; they remain neutral non-electrolytes.\n• Option (D): Incorrect. Acids dissolve and ionize in water; they do not separate by instantaneous evaporation.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 4000),
    ),
    Question(
      id: "sci_ch2_p28_q02",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 28)] Why does an aqueous solution of an acid conduct electricity?",
      options: const [
        QuestionOption(id: "A", text: "Because it dissociates into mobile cations (\$\\text{H}^+_3\\text{O}\$) and anions that carry electric current through the liquid.", isCorrect: true),
        QuestionOption(id: "B", text: "Because pure water molecules contain free metallic electrons that transmit current.", isCorrect: false),
        QuestionOption(id: "C", text: "Because the acid dissolves the copper connecting wires to complete the physical circuit.", isCorrect: false),
        QuestionOption(id: "D", text: "Because acid molecules heat the solution to glowing incandescent temperatures.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Because it dissociates into mobile cations (\$\\text{H}^+_3\\text{O}\$) and anions that carry electric current through the liquid.\n\nScientific Principle / Key Concept:\nElectrolytic conduction in solution requires mobile ions. Acids ionize into \$\\text{H}^+(aq)\$ and corresponding anions, which migrate toward electrodes under an electric field.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Water has covalent bonding and lacks free metallic electrons.\n• Option (C): Incorrect. Conduction is ionic through the electrolyte, not due to dissolving external wiring.\n• Option (D): Incorrect. Aqueous electrical conduction does not rely on thermal incandescence.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 5000),
    ),
    Question(
      id: "sci_ch2_p28_q03",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 28)] Why does dry \$\\text{HCl}\$ gas not change the colour of dry litmus paper?",
      options: const [
        QuestionOption(id: "A", text: "In the absence of moisture, \$\\text{HCl}\$ cannot dissociate to form \$\\text{H}^+\$ ions which are responsible for acidic color change.", isCorrect: true),
        QuestionOption(id: "B", text: "Dry \$\\text{HCl}\$ gas is a strong base that neutralizes red litmus immediately.", isCorrect: false),
        QuestionOption(id: "C", text: "Litmus paper dye is insoluble in all gaseous states of matter.", isCorrect: false),
        QuestionOption(id: "D", text: "Dry \$\\text{HCl}\$ gas decomposes dry litmus dye into free nitrogen gas.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) In the absence of moisture, \$\\text{HCl}\$ cannot dissociate to form \$\\text{H}^+\$ ions which are responsible for acidic color change.\n\nScientific Principle / Key Concept:\nLitmus indicator color change is triggered exclusively by hydrogen/hydronium ions. Dry \$\\text{HCl}\$ exists as covalent molecules and cannot ionize without water.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. \$\\text{HCl}\$ is an acidic gas, not a base.\n• Option (C): Incorrect. Moist litmus paper readily changes color in dry \$\\text{HCl}\$ gas because moisture provides the medium for ionization.\n• Option (D): Incorrect. Litmus paper is not degraded into nitrogen gas by dry \$\\text{HCl}\$.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 6000),
    ),
    Question(
      id: "sci_ch2_p28_q04",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 28)] While diluting an acid, why is it strictly recommended that acid should be added to water and never water to acid?",
      options: const [
        QuestionOption(id: "A", text: "The dilution of acid is highly exothermic; adding water to concentrated acid causes violent boiling, acid splashes, and glass breakage.", isCorrect: true),
        QuestionOption(id: "B", text: "Adding water to acid converts the acid into a non-reactive neutral hydrocarbon.", isCorrect: false),
        QuestionOption(id: "C", text: "Water is denser than acid and sinks immediately, preventing any chemical interaction.", isCorrect: false),
        QuestionOption(id: "D", text: "Acid dissolves water molecules into oxygen and hydrogen gas, causing a gas fire.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The dilution of acid is highly exothermic; adding water to concentrated acid causes violent boiling, acid splashes, and glass breakage.\n\nScientific Principle / Key Concept:\nMixing concentrated acid with water releases massive heat. Adding acid slowly to a large volume of water with constant stirring allows water to absorb and dissipate the heat safely.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Dilution is a physical hydration process, not hydrocarbon synthesis.\n• Option (C): Incorrect. Concentrated sulphuric acid is denser than water (\$1.84\\text{ g/cm}^3\$ vs \$1.0\\text{ g/cm}^3\$).\n• Option (D): Incorrect. Dilution does not electrolyze water into flammable hydrogen and oxygen gases.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 7000),
    ),
    Question(
      id: "sci_ch2_p28_q05",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 28)] How is the concentration of hydronium ions (\$\\text{H}_3\\text{O}^+\$) affected when a solution of an acid is diluted?",
      options: const [
        QuestionOption(id: "A", text: "The concentration of hydronium ions per unit volume decreases.", isCorrect: true),
        QuestionOption(id: "B", text: "The concentration of hydronium ions per unit volume increases significantly.", isCorrect: false),
        QuestionOption(id: "C", text: "The concentration remains completely unaffected because water cannot interact with ions.", isCorrect: false),
        QuestionOption(id: "D", text: "Hydronium ions are completely converted into molecular hydroxide ions.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The concentration of hydronium ions per unit volume decreases.\n\nScientific Principle / Key Concept:\nOn adding water to an acid solution, the total volume increases while the number of \$\\text{H}_3\\text{O}^+\$ ions remains constant, so their concentration per unit volume decreases.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Dilution increases volume, decreasing concentration.\n• Option (C): Incorrect. Concentration is inversely proportional to volume (\$C = n/V\$).\n• Option (D): Incorrect. Diluting an acid decreases \$[\text{H}_3\text{O}^+]\$, but does not make the solution basic.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 8000),
    ),
    Question(
      id: "sci_ch2_p28_q06",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 28)] How is the concentration of hydroxide ions (\$\\text{OH}^-\$) affected when excess base is dissolved in a solution of sodium hydroxide?",
      options: const [
        QuestionOption(id: "A", text: "The concentration of hydroxide ions per unit volume increases.", isCorrect: true),
        QuestionOption(id: "B", text: "The concentration of hydroxide ions decreases due to ionic saturation precipitation.", isCorrect: false),
        QuestionOption(id: "C", text: "Hydroxide ions decompose into gaseous oxygen and hydrogen.", isCorrect: false),
        QuestionOption(id: "D", text: "The concentration remains unaltered as sodium hydroxide cannot dissociate further.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The concentration of hydroxide ions per unit volume increases.\n\nScientific Principle / Key Concept:\nDissolving more base adds additional \$\\text{OH}^-\$ ions to the fixed volume, thereby increasing \$[\text{OH}^-]\$ per unit volume.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Adding solute before saturation increases concentration.\n• Option (C): Incorrect. Base dissolution does not cause decomposition into gaseous elements.\n• Option (D): Incorrect. Added \$\\text{NaOH}\$ dissociates directly into \$\\text{Na}^+\$ and \$\\text{OH}^-\$, increasing the ion count.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 9000),
    ),
    Question(
      id: "sci_ch2_p33_q01",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 33)] You have two solutions, A and B. The pH of solution A is 6 and pH of solution B is 8. Which solution has higher hydrogen ion concentration, and which is acidic / basic?",
      options: const [
        QuestionOption(id: "A", text: "Solution A has higher \$[\\text{H}^+]\$ concentration; Solution A is acidic and Solution B is basic.", isCorrect: true),
        QuestionOption(id: "B", text: "Solution B has higher \$[\\text{H}^+]\$ concentration; Solution B is acidic and Solution A is basic.", isCorrect: false),
        QuestionOption(id: "C", text: "Both solutions have equal \$[\\text{H}^+]\$ concentration because they are symmetrically spaced around pH 7.", isCorrect: false),
        QuestionOption(id: "D", text: "Solution A is neutral, while Solution B is strongly acidic.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Solution A has higher \$[\\text{H}^+]\$ concentration; Solution A is acidic and Solution B is basic.\n\nScientific Principle / Key Concept:\n\$\\text{pH} = -\\log_{10}[\\text{H}^+]\$. A lower pH value denotes higher \$[\\text{H}^+]\$. \$\\text{pH} < 7\$ is acidic (Solution A), and \$\\text{pH} > 7\$ is basic (Solution B).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Higher pH means lower hydrogen ion concentration, not higher.\n• Option (C): Incorrect. Solution A has \$[\\text{H}^+] = 10^{-6}\\text{ M}\$ while B has \$10^{-8}\\text{ M}\$, a 100-fold difference.\n• Option (D): Incorrect. Neutral pH is exactly 7.0 at \$25^\\circ\\text{C}\$.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 10000),
    ),
    Question(
      id: "sci_ch2_p33_q02",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 33)] What effect does increasing the concentration of \$\\text{H}^+(aq)\$ ions have on the nature of a solution?",
      options: const [
        QuestionOption(id: "A", text: "The solution becomes more strongly acidic and its pH value decreases.", isCorrect: true),
        QuestionOption(id: "B", text: "The solution becomes alkaline and its pH value rises above 12.", isCorrect: false),
        QuestionOption(id: "C", text: "The solution becomes neutral as excess hydrogen ions cancel each other out.", isCorrect: false),
        QuestionOption(id: "D", text: "The electrical conductivity of the solution drops to zero.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The solution becomes more strongly acidic and its pH value decreases.\n\nScientific Principle / Key Concept:\nAcidity is directly determined by \$[\\text{H}^+(aq)]\$. As \$[\\text{H}^+]\$ rises, the acidity increases and \$\\text{pH}\$ drops.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Alkalinity corresponds to higher \$[\\text{OH}^-]\$, not higher \$[\\text{H}^+]\$.\n• Option (C): Incorrect. Hydrogen ions do not cancel each other out.\n• Option (D): Incorrect. More ions increase electrical conductivity.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 11000),
    ),
    Question(
      id: "sci_ch2_p33_q03",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 33)] Do basic solutions also have \$\\text{H}^+(aq)\$ ions? If yes, why are they classified as basic?",
      options: const [
        QuestionOption(id: "A", text: "Yes, basic solutions contain \$\\text{H}^+\$ ions from water auto-ionization, but \$[\\text{OH}^-] \\gg [\\text{H}^+]\$.", isCorrect: true),
        QuestionOption(id: "B", text: "No, basic solutions contain zero \$\\text{H}^+\$ ions because bases destroy all protons.", isCorrect: false),
        QuestionOption(id: "C", text: "Yes, but \$\\text{H}^+\$ ions in bases carry negative charges instead of positive charges.", isCorrect: false),
        QuestionOption(id: "D", text: "No, bases are composed exclusively of pure sodium metal atoms.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Yes, basic solutions contain \$\\text{H}^+\$ ions from water auto-ionization, but \$[\\text{OH}^-] \\gg [\\text{H}^+]\$.\n\nScientific Principle / Key Concept:\nIn all aqueous solutions, \$[\\text{H}^+][\\text{OH}^-] = K_w = 10^{-14}\$. Basic solutions have \$\\text{H}^+\$ ions, but the concentration of hydroxide ions is far greater.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Water always contains an equilibrium amount of \$\\text{H}^+\$ ions.\n• Option (C): Incorrect. Hydrogen ions are always positively charged cations (\$H^+\$).\n• Option (D): Incorrect. Bases are compounds like hydroxides or oxides, not pure sodium metal.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 12000),
    ),
    Question(
      id: "sci_ch2_p33_q04",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Page 33)] Under what soil condition would a farmer treat the soil of his fields with quick lime (\$\\text{CaO}\$), slaked lime (\$\\text{Ca(OH)}_2\$), or chalk (\$\\text{CaCO}_3\$)?",
      options: const [
        QuestionOption(id: "A", text: "When the soil is overly acidic (pH too low for optimal crop growth).", isCorrect: true),
        QuestionOption(id: "B", text: "When the soil is excessively alkaline with pH greater than 10.", isCorrect: false),
        QuestionOption(id: "C", text: "When the soil is saturated with excessive moisture from flooding.", isCorrect: false),
        QuestionOption(id: "D", text: "When the farmer wants to dissolve earthworms and microbial organic matter.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) When the soil is overly acidic (pH too low for optimal crop growth).\n\nScientific Principle / Key Concept:\nQuick lime (\$\\text{CaO}\$), slaked lime (\$\\text{Ca(OH)}_2\$), and chalk (\$\\text{CaCO}_3\$) are basic in nature and neutralize excessive soil acidity.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Adding basic calcium compounds to alkaline soil would make it even more alkaline.\n• Option (C): Incorrect. Lining is applied to regulate chemical pH, not for physical flood drainage.\n• Option (D): Incorrect. The purpose is creating an optimal pH (around 6.5–7.5) for plant nutrition.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 13000),
    ),
    Question(
      id: "sci_ch2_p34_q01",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Pages 34-35)] What is the common chemical name of the compound \$\\text{CaOCl}_2\$?",
      options: const [
        QuestionOption(id: "A", text: "Bleaching powder", isCorrect: true),
        QuestionOption(id: "B", text: "Baking soda", isCorrect: false),
        QuestionOption(id: "C", text: "Washing soda", isCorrect: false),
        QuestionOption(id: "D", text: "Plaster of Paris", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Bleaching powder\n\nScientific Principle / Key Concept:\nCalcium oxychloride (\$\\text{CaOCl}_2\$) is commonly known as bleaching powder.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Baking soda is sodium hydrogencarbonate (\$\\text{NaHCO}_3\$).\n• Option (C): Incorrect. Washing soda is sodium carbonate decahydrate (\$\\text{Na}_2\\text{CO}_3 \\cdot 10\\text{H}_2\\text{O}\$).\n• Option (D): Incorrect. Plaster of Paris is calcium sulphate hemihydrate (\$\\text{CaSO}_4 \\cdot \\frac{1}{2}\\text{H}_2\\text{O}\$).",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 14000),
    ),
    Question(
      id: "sci_ch2_p34_q02",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Pages 34-35)] Name the substance which on treatment with chlorine gas yields bleaching powder.",
      options: const [
        QuestionOption(id: "A", text: "Dry slaked lime [\$\\text{Ca(OH)}_2\$]", isCorrect: true),
        QuestionOption(id: "B", text: "Limestone [\$\\text{CaCO}_3\$]", isCorrect: false),
        QuestionOption(id: "C", text: "Gypsum [\$\\text{CaSO}_4 \\cdot 2\\text{H}_2\\text{O}\$]", isCorrect: false),
        QuestionOption(id: "D", text: "Sodium chloride [\$\\text{NaCl}\$]", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Dry slaked lime [\$\\text{Ca(OH)}_2\$]\n\nScientific Principle / Key Concept:\nBleaching powder is manufactured by passing chlorine gas over dry slaked lime: \$\\text{Ca(OH)}_2 + \\text{Cl}_2 \\rightarrow \\text{CaOCl}_2 + \\text{H}_2\\text{O}\$.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Limestone does not react with chlorine under standard conditions to form bleaching powder.\n• Option (C): Incorrect. Gypsum is hydrated calcium sulphate, not the precursor for bleaching powder.\n• Option (D): Incorrect. \$\\text{NaCl}\$ is used to generate chlorine gas via chlor-alkali, but the reactant that absorbs chlorine is slaked lime.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 15000),
    ),
    Question(
      id: "sci_ch2_p34_q03",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Pages 34-35)] Which sodium compound is used for softening hard water?",
      options: const [
        QuestionOption(id: "A", text: "Washing soda (Sodium carbonate decahydrate, \$\\text{Na}_2\\text{CO}_3 \\cdot 10\\text{H}_2\\text{O}\$)", isCorrect: true),
        QuestionOption(id: "B", text: "Sodium chloride (\$\\text{NaCl}\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Sodium hydroxide (\$\\text{NaOH}\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Sodium nitrate (\$\\text{NaNO}_3\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Washing soda (Sodium carbonate decahydrate, \$\\text{Na}_2\\text{CO}_3 \\cdot 10\\text{H}_2\\text{O}\$)\n\nScientific Principle / Key Concept:\nWashing soda reacts with dissolved calcium and magnesium ions in hard water, precipitating them as insoluble carbonates.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Sodium chloride does not precipitate calcium and magnesium ions to soften water.\n• Option (C): Incorrect. \$\\text{NaOH}\$ is caustic soda, used in soap manufacture, not primary domestic water softening.\n• Option (D): Incorrect. Sodium nitrate is a soluble fertilizer and does not soften hard water.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 16000),
    ),
    Question(
      id: "sci_ch2_p34_q04",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Pages 34-35)] What happens when a solution of sodium hydrogencarbonate is heated? Give the balanced equation.",
      options: const [
        QuestionOption(id: "A", text: "It decomposes to form sodium carbonate, water, and carbon dioxide: \$2\\text{NaHCO}_3 \\xrightarrow{\\Delta} \\text{Na}_2\\text{CO}_3 + \\text{H}_2\\text{O} + \\text{CO}_2\$", isCorrect: true),
        QuestionOption(id: "B", text: "It oxidizes into sodium peroxide and hydrogen gas: \$2\\text{NaHCO}_3 \\xrightarrow{\\Delta} \\text{Na}_2\\text{O}_2 + 2\\text{CO} + \\text{H}_2\$", isCorrect: false),
        QuestionOption(id: "C", text: "It sublimes into sodium metal vapors without any chemical reaction.", isCorrect: false),
        QuestionOption(id: "D", text: "It reduces to form sodium hydride and oxygen gas: \$\\text{NaHCO}_3 \\xrightarrow{\\Delta} \\text{NaH} + \\text{CO}_2 + \\text{O}_2\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) It decomposes to form sodium carbonate, water, and carbon dioxide: \$2\\text{NaHCO}_3 \\xrightarrow{\\Delta} \\text{Na}_2\\text{CO}_3 + \\text{H}_2\\text{O} + \\text{CO}_2\$\n\nScientific Principle / Key Concept:\nThermal decomposition of sodium hydrogencarbonate releases carbon dioxide gas, which causes bread and cakes to rise.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Heating hydrogencarbonates yields carbonate and \$\\text{CO}_2\$, not peroxide.\n• Option (C): Incorrect. \$\\text{NaHCO}_3\$ undergoes chemical decomposition, not physical sublimation.\n• Option (D): Incorrect. Sodium hydride is not formed by heating baking soda.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 17000),
    ),
    Question(
      id: "sci_ch2_p34_q05",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[QUESTIONS (Pages 34-35)] Write the balanced chemical equation showing the reaction between Plaster of Paris and water.",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{CaSO}_4 \\cdot \\frac{1}{2}\\text{H}_2\\text{O} + 1\\frac{1}{2}\\text{H}_2\\text{O} \\rightarrow \\text{CaSO}_4 \\cdot 2\\text{H}_2\\text{O}\$", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{CaSO}_4 \\cdot 2\\text{H}_2\\text{O} + \\text{H}_2\\text{O} \\rightarrow \\text{CaSO}_4 \\cdot 3\\text{H}_2\\text{O}\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{CaSO}_4 + 2\\text{H}_2\\text{O} \\rightarrow \\text{Ca(OH)}_2 + \\text{H}_2\\text{SO}_4\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{CaSO}_4 \\cdot \\frac{1}{2}\\text{H}_2\\text{O} \\rightarrow \\text{CaO} + \\text{SO}_3 + \\frac{1}{2}\\text{H}_2\\text{O}\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{CaSO}_4 \\cdot \\frac{1}{2}\\text{H}_2\\text{O} + 1\\frac{1}{2}\\text{H}_2\\text{O} \\rightarrow \\text{CaSO}_4 \\cdot 2\\text{H}_2\\text{O}\$\n\nScientific Principle / Key Concept:\nPlaster of Paris (calcium sulphate hemihydrate) combines with one and a half molecules of water to reform gypsum (a hard solid mass).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. \$\\text{CaSO}_4 \\cdot 2\\text{H}_2\\text{O}\$ is gypsum, not Plaster of Paris.\n• Option (C): Incorrect. Anhydrous calcium sulphate does not hydrolyze into slaked lime and sulphuric acid.\n• Option (D): Incorrect. This represents destructive pyrolytic decomposition, not reaction with water.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 18000),
    ),
    Question(
      id: "sci_ch2_ex01",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] A solution turns red litmus blue, its pH is likely to be:",
      options: const [
        QuestionOption(id: "A", text: "1", isCorrect: false),
        QuestionOption(id: "B", text: "4", isCorrect: false),
        QuestionOption(id: "C", text: "5", isCorrect: false),
        QuestionOption(id: "D", text: "10", isCorrect: true),
      ],
      stepByStepSolution: "Correct Answer: (D) 10\n\nScientific Principle / Key Concept:\nBasic solutions (pH > 7) turn red litmus blue. Among the given options, only pH 10 is basic.\n\nDetailed Distractor & Misconception Analysis:\n• Option (A): Incorrect. pH 1 is strongly acidic; turns blue litmus red.\n• Option (B): Incorrect. pH 4 is acidic; leaves red litmus red.\n• Option (C): Incorrect. pH 5 is acidic; does not turn red litmus blue.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 19000),
    ),
    Question(
      id: "sci_ch2_ex02",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] A solution reacts with crushed egg-shells to give a gas that turns lime-water milky. The solution contains:",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{NaCl}\$", isCorrect: false),
        QuestionOption(id: "B", text: "\$\\text{HCl}\$", isCorrect: true),
        QuestionOption(id: "C", text: "\$\\text{LiCl}\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{KCl}\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (B) \$\\text{HCl}\$\n\nScientific Principle / Key Concept:\nEgg-shells are calcium carbonate (\$\\text{CaCO}_3\$). \$\\text{HCl}\$ reacts with \$\\text{CaCO}_3\$ releasing \$\\text{CO}_2\$, which turns lime water milky.\n\nDetailed Distractor & Misconception Analysis:\n• Option (A): Incorrect. Neutral salt; does not react with egg-shells.\n• Option (C): Incorrect. Neutral salt; does not evolve \$\\text{CO}_2\$ from carbonate.\n• Option (D): Incorrect. Neutral salt; unreactive toward calcium carbonate.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 20000),
    ),
    Question(
      id: "sci_ch2_ex03",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] \$10\\text{ mL}\$ of a solution of \$\\text{NaOH}\$ is completely neutralised by \$8\\text{ mL}\$ of a given solution of \$\\text{HCl}\$. If we take \$20\\text{ mL}\$ of the same solution of \$\\text{NaOH}\$, the amount of \$\\text{HCl}\$ solution required to neutralise it will be:",
      options: const [
        QuestionOption(id: "A", text: "\$4\\text{ mL}\$", isCorrect: false),
        QuestionOption(id: "B", text: "\$8\\text{ mL}\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$12\\text{ mL}\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$16\\text{ mL}\$", isCorrect: true),
      ],
      stepByStepSolution: "Correct Answer: (D) \$16\\text{ mL}\$\n\nScientific Principle / Key Concept:\nNeutralisation stoichiometry is linear: \$20\\text{ mL } \\text{NaOH} = 2 \\times 10\\text{ mL}\$, requiring \$2 \\times 8\\text{ mL} = 16\\text{ mL}\$ of \$\\text{HCl}\$.\n\nDetailed Distractor & Misconception Analysis:\n• Option (A): Incorrect. Halving acid volume would only neutralize \$5\\text{ mL}\$ of base.\n• Option (B): Incorrect. This amount only neutralizes \$10\\text{ mL}\$ of \$\\text{NaOH}\$.\n• Option (C): Incorrect. Neutralizes \$15\\text{ mL}\$ of \$\\text{NaOH}\$.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 21000),
    ),
    Question(
      id: "sci_ch2_ex04",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Which one of the following types of medicines is used for treating indigestion?",
      options: const [
        QuestionOption(id: "A", text: "Antibiotic", isCorrect: false),
        QuestionOption(id: "B", text: "Analgesic", isCorrect: false),
        QuestionOption(id: "C", text: "Antacid", isCorrect: true),
        QuestionOption(id: "D", text: "Antiseptic", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (C) Antacid\n\nScientific Principle / Key Concept:\nIndigestion is caused by excess gastric \$\\text{HCl}\$. Antacids are mild bases (e.g., milk of magnesia) that neutralize excess acid.\n\nDetailed Distractor & Misconception Analysis:\n• Option (A): Incorrect. Used to treat bacterial infections, not stomach acidity.\n• Option (B): Incorrect. Used for pain relief.\n• Option (D): Incorrect. Used on living tissues to prevent microbial infection.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 22000),
    ),
    Question(
      id: "sci_ch2_ex05_a",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Write the balanced chemical equation for the reaction: Dilute sulphuric acid reacts with zinc granules.",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{Zn}(s) + \\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{ZnSO}_4(aq) + \\text{H}_2(g)\$", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{Zn}(s) + \\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{ZnO}(s) + \\text{SO}_2(g) + \\text{H}_2\\text{O}(l)\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$2\\text{Zn}(s) + \\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{Zn}_2\\text{SO}_4(aq) + \\text{H}_2(g)\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{Zn}(s) + 2\\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{Zn(HSO}_4)_2(aq) + \\text{H}_2(g)\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{Zn}(s) + \\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{ZnSO}_4(aq) + \\text{H}_2(g)\$\n\nScientific Principle / Key Concept:\nZinc displaces hydrogen from dilute sulphuric acid forming zinc sulphate and hydrogen gas.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. This requires hot concentrated sulphuric acid, not dilute.\n• Option (C): Incorrect. Zinc valency is \$+2\$; \$\\text{Zn}_2\\text{SO}_4\$ is an incorrect formula.\n• Option (D): Incorrect. Standard reaction yields neutral sulphate, not bisulphate.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 23000),
    ),
    Question(
      id: "sci_ch2_ex05_b",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Write the balanced chemical equation for the reaction: Dilute hydrochloric acid reacts with magnesium ribbon.",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{Mg}(s) + 2\\text{HCl}(aq) \\rightarrow \\text{MgCl}_2(aq) + \\text{H}_2(g)\$", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{Mg}(s) + \\text{HCl}(aq) \\rightarrow \\text{MgCl}(aq) + \\text{H}(g)\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{Mg}(s) + 2\\text{HCl}(aq) \\rightarrow \\text{MgCl}_2(aq) + 2\\text{H}_2(g)\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$2\\text{Mg}(s) + 2\\text{HCl}(aq) \\rightarrow 2\\text{MgCl}(aq) + \\text{H}_2(g)\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{Mg}(s) + 2\\text{HCl}(aq) \\rightarrow \\text{MgCl}_2(aq) + \\text{H}_2(g)\$\n\nScientific Principle / Key Concept:\nMagnesium reacts vigorously with dilute hydrochloric acid producing magnesium chloride and hydrogen gas.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Magnesium is divalent (\$\text{MgCl}_2\$) and hydrogen is diatomic (\$\text{H}_2\$).\n• Option (C): Incorrect. Hydrogen atoms are unbalanced.\n• Option (D): Incorrect. Formula \$\\text{MgCl}\$ is incorrect.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 24000),
    ),
    Question(
      id: "sci_ch2_ex05_c",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Write the balanced chemical equation for the reaction: Dilute sulphuric acid reacts with aluminium powder.",
      options: const [
        QuestionOption(id: "A", text: "\$2\\text{Al}(s) + 3\\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{Al}_2(\\text{SO}_4)_3(aq) + 3\\text{H}_2(g)\$", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{Al}(s) + \\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{AlSO}_4(aq) + \\text{H}_2(g)\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$2\\text{Al}(s) + \\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{Al}_2\\text{SO}_4(aq) + \\text{H}_2(g)\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{Al}(s) + 3\\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{Al(SO}_4)_3(aq) + 3\\text{H}_2(g)\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$2\\text{Al}(s) + 3\\text{H}_2\\text{SO}_4(aq) \\rightarrow \\text{Al}_2(\\text{SO}_4)_3(aq) + 3\\text{H}_2(g)\$\n\nScientific Principle / Key Concept:\nTwo moles of trivalent aluminium react with three moles of sulphuric acid to produce aluminium sulphate and three moles of hydrogen.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. \$\\text{AlSO}_4\$ violates aluminium \$+3\$ valency.\n• Option (C): Incorrect. Incorrect chemical formula and unbalanced atoms.\n• Option (D): Incorrect. Formula \$\\text{Al(SO}_4)_3\$ is chemically invalid.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 25000),
    ),
    Question(
      id: "sci_ch2_ex05_d",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Write the balanced chemical equation for the reaction: Dilute hydrochloric acid reacts with iron filings.",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{Fe}(s) + 2\\text{HCl}(aq) \\rightarrow \\text{FeCl}_2(aq) + \\text{H}_2(g)\$", isCorrect: true),
        QuestionOption(id: "B", text: "\$2\\text{Fe}(s) + 6\\text{HCl}(aq) \\rightarrow 2\\text{FeCl}_3(aq) + 3\\text{H}_2(g)\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{Fe}(s) + \\text{HCl}(aq) \\rightarrow \\text{FeCl}(aq) + \\text{H}(g)\$", isCorrect: false),
        QuestionOption(id: "D", text: "\$\\text{Fe}(s) + 4\\text{HCl}(aq) \\rightarrow \\text{FeCl}_4(aq) + 2\\text{H}_2(g)\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{Fe}(s) + 2\\text{HCl}(aq) \\rightarrow \\text{FeCl}_2(aq) + \\text{H}_2(g)\$\n\nScientific Principle / Key Concept:\nReaction of iron with dilute hydrochloric acid forms ferrous chloride (iron(II) chloride) and hydrogen gas.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Dilute \$\\text{HCl}\$ yields iron(II) chloride, not iron(III) chloride.\n• Option (C): Incorrect. Monoatomic hydrogen and \$\\text{FeCl}\$ are chemically incorrect.\n• Option (D): Incorrect. \$\\text{FeCl}_4\$ does not form in standard aqueous displacement.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 26000),
    ),
    Question(
      id: "sci_ch2_ex07",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Why does distilled water not conduct electricity, whereas rain water does?",
      options: const [
        QuestionOption(id: "A", text: "Distilled water is pure and devoid of ionic species, whereas rain water dissolves atmospheric gases like \$\\text{CO}_2\$ and \$\\text{SO}_2\$ forming conducting ions like \$\\text{H}^+\$ and \$\\text{CO}_3^{2-}\$.", isCorrect: true),
        QuestionOption(id: "B", text: "Distilled water contains excessive oil molecules that insulate against current.", isCorrect: false),
        QuestionOption(id: "C", text: "Rain water contains free copper electrons transferred from clouds.", isCorrect: false),
        QuestionOption(id: "D", text: "Distilled water is frozen at molecular levels, preventing current flow.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Distilled water is pure and devoid of ionic species, whereas rain water dissolves atmospheric gases like \$\\text{CO}_2\$ and \$\\text{SO}_2\$ forming conducting ions like \$\\text{H}^+\$ and \$\\text{CO}_3^{2-}\$.\n\nScientific Principle / Key Concept:\nElectrical conduction requires mobile ions. Distilled water contains virtually no free ions, while rain water forms weak acids (e.g., \$\\text{H}_2\\text{CO}_3\$) providing free ions.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Distilled water is pure water without oils.\n• Option (C): Incorrect. Conduction in rain water is ionic, not metallic copper conduction.\n• Option (D): Incorrect. Liquid distilled water is not frozen.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 27000),
    ),
    Question(
      id: "sci_ch2_ex08",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Why do acids not show acidic behaviour in the absence of water?",
      options: const [
        QuestionOption(id: "A", text: "Dissociation of acid molecules into hydrogen ions (\$\\text{H}^+\$) occurs strictly in the presence of water, as water stabilizes \$\\text{H}^+\$ as hydronium (\$\\text{H}_3\\text{O}^+\$).", isCorrect: true),
        QuestionOption(id: "B", text: "In the absence of water, acids freeze solid and turn into alkaline hydroxides.", isCorrect: false),
        QuestionOption(id: "C", text: "Water acts as a fuel that burns acid molecules into acidic fumes.", isCorrect: false),
        QuestionOption(id: "D", text: "Dry acid molecules are blocked by atmospheric nitrogen from changing litmus.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Dissociation of acid molecules into hydrogen ions (\$\\text{H}^+\$) occurs strictly in the presence of water, as water stabilizes \$\\text{H}^+\$ as hydronium (\$\\text{H}_3\\text{O}^+\$).\n\nScientific Principle / Key Concept:\nProtons cannot exist independently; they must coordinate with water to form \$\\text{H}_3\\text{O}^+\$. Without water, no ionization occurs.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Acids do not turn into alkaline hydroxides.\n• Option (C): Incorrect. Acid behavior is ionic, not combustion-driven.\n• Option (D): Incorrect. Nitrogen does not chemically block acid ionization.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 28000),
    ),
    Question(
      id: "sci_ch2_ex09",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Five solutions A, B, C, D and E tested with universal indicator showed pH values 4, 1, 11, 7 and 9 respectively. Which solution is neutral and which is strongly acidic?",
      options: const [
        QuestionOption(id: "A", text: "Solution D (pH 7) is neutral; Solution B (pH 1) is strongly acidic.", isCorrect: true),
        QuestionOption(id: "B", text: "Solution C (pH 11) is neutral; Solution A (pH 4) is strongly acidic.", isCorrect: false),
        QuestionOption(id: "C", text: "Solution D (pH 7) is strongly alkaline; Solution E (pH 9) is neutral.", isCorrect: false),
        QuestionOption(id: "D", text: "Solution B (pH 1) is neutral; Solution D (pH 7) is strongly acidic.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Solution D (pH 7) is neutral; Solution B (pH 1) is strongly acidic.\n\nScientific Principle / Key Concept:\npH 7 indicates a neutral solution (D). The lowest pH value (1) denotes the highest \$[\text{H}^+]\$ concentration, which is strongly acidic (B).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. pH 11 is strongly alkaline, not neutral.\n• Option (C): Incorrect. pH 7 is neutral; pH 9 is weakly alkaline.\n• Option (D): Incorrect. Inverted logic; pH 1 is strongly acidic.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 29000),
    ),
    Question(
      id: "sci_ch2_ex10",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Equal lengths of magnesium ribbons are placed in test tubes A (with \$\\text{HCl}\$) and B (with \$\\text{CH}_3\\text{COOH}\$). In which test tube will fizzing occur more vigorously and why?",
      options: const [
        QuestionOption(id: "A", text: "Test tube A; \$\\text{HCl}\$ is a strong acid that completely ionizes, producing a much higher \$[\\text{H}^+]\$ concentration than weak \$\\text{CH}_3\\text{COOH}\$.", isCorrect: true),
        QuestionOption(id: "B", text: "Test tube B; acetic acid is an organic acid containing more carbon atoms which accelerate fizzing.", isCorrect: false),
        QuestionOption(id: "C", text: "Both test tubes will fizz at identical rates because equal lengths of magnesium were used.", isCorrect: false),
        QuestionOption(id: "D", text: "Test tube B; acetic acid dissolves the glass test tube to produce excess gas.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Test tube A; \$\\text{HCl}\$ is a strong acid that completely ionizes, producing a much higher \$[\\text{H}^+]\$ concentration than weak \$\\text{CH}_3\\text{COOH}\$.\n\nScientific Principle / Key Concept:\nHigher \$[\text{H}^+]\$ in strong acid \$\\text{HCl}\$ leads to a faster reaction rate with magnesium ribbon, evolving \$\\text{H}_2\$ gas much more vigorously.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Acetic acid is a weak acid with lower \$[\text{H}^+]\$, reacting much more slowly.\n• Option (C): Incorrect. Reaction rate depends heavily on the concentration of \$\\text{H}^+\$ ions.\n• Option (D): Incorrect. Acetic acid does not dissolve laboratory borosilicate glass.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 30000),
    ),
    Question(
      id: "sci_ch2_ex11",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Fresh milk has a pH of 6. How will its pH change as it turns into curd, and why?",
      options: const [
        QuestionOption(id: "A", text: "Its pH decreases below 6 because bacteria convert lactose into lactic acid, which increases \$[\\text{H}^+]\$.", isCorrect: true),
        QuestionOption(id: "B", text: "Its pH increases above 10 because curd is strongly alkaline.", isCorrect: false),
        QuestionOption(id: "C", text: "Its pH remains fixed at exactly 6 because milk fats buffer against all acid changes.", isCorrect: false),
        QuestionOption(id: "D", text: "Its pH fluctuates between 0 and 14 every minute.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Its pH decreases below 6 because bacteria convert lactose into lactic acid, which increases \$[\\text{H}^+]\$.\n\nScientific Principle / Key Concept:\nLactobacillus bacteria ferment lactose sugar into lactic acid. Acid formation increases \$[\text{H}^+]\$ and decreases the pH below 6.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Curd is sour and acidic, not alkaline.\n• Option (C): Incorrect. pH drops significantly as lactic acid builds up.\n• Option (D): Incorrect. The pH drop is steady and irreversible under normal conditions.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 31000),
    ),
    Question(
      id: "sci_ch2_ex12_a",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] A milkman adds a very small amount of baking soda to fresh milk. Why does he shift the pH from 6 to slightly alkaline?",
      options: const [
        QuestionOption(id: "A", text: "To prevent the milk from turning sour quickly, as alkaline milk takes longer to reach the acidic curdling threshold.", isCorrect: true),
        QuestionOption(id: "B", text: "To make the milk sweeter and carbonated like a fizzy soft drink.", isCorrect: false),
        QuestionOption(id: "C", text: "To bleach the natural yellow tint of milk into pure bright white.", isCorrect: false),
        QuestionOption(id: "D", text: "To increase the boiling point of milk above \$300^\\circ\\text{C}\$.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) To prevent the milk from turning sour quickly, as alkaline milk takes longer to reach the acidic curdling threshold.\n\nScientific Principle / Key Concept:\nMaking milk slightly alkaline neutralizes initial lactic acid, preserving freshness during transport in warm weather.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. The trace amount does not sweeten or carbonate milk for beverage flavor.\n• Option (C): Incorrect. Baking soda is a mild alkali, not a bleaching agent.\n• Option (D): Incorrect. Boiling point elevation by trace solute is negligible.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 32000),
    ),
    Question(
      id: "sci_ch2_ex12_b",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Why does this milk (with added baking soda) take a much longer time to set as curd?",
      options: const [
        QuestionOption(id: "A", text: "The lactic acid produced by bacteria must first neutralize the added alkaline baking soda before the pH can drop enough to curdle proteins.", isCorrect: true),
        QuestionOption(id: "B", text: "Baking soda permanently kills all lactic acid bacteria in the milk.", isCorrect: false),
        QuestionOption(id: "C", text: "Baking soda turns milk into a solid crystal that cannot coagulate.", isCorrect: false),
        QuestionOption(id: "D", text: "Baking soda converts milk proteins into gaseous carbon dioxide.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The lactic acid produced by bacteria must first neutralize the added alkaline baking soda before the pH can drop enough to curdle proteins.\n\nScientific Principle / Key Concept:\nMilk coagulates into curd at an acidic pH. The added \$\\text{NaHCO}_3\$ buffers against acid, requiring extra time for sufficient lactic acid to accumulate.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Trace baking soda does not sterilize milk; bacteria continue to grow.\n• Option (C): Incorrect. Milk remains liquid until acidification causes casein precipitation.\n• Option (D): Incorrect. Proteins are not converted into gas.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 33000),
    ),
    Question(
      id: "sci_ch2_ex13",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Why should Plaster of Paris be stored in a moisture-proof container?",
      options: const [
        QuestionOption(id: "A", text: "Because it readily absorbs atmospheric moisture to set into hard, unusable gypsum mass.", isCorrect: true),
        QuestionOption(id: "B", text: "Because moisture causes Plaster of Paris to ignite into an explosive flame.", isCorrect: false),
        QuestionOption(id: "C", text: "Because moisture evaporates Plaster of Paris into toxic gaseous sulphur.", isCorrect: false),
        QuestionOption(id: "D", text: "Because water molecules chemically dissolve gypsum into liquid metallic calcium.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Because it readily absorbs atmospheric moisture to set into hard, unusable gypsum mass.\n\nScientific Principle / Key Concept:\n\$\\text{CaSO}_4 \\cdot \\frac{1}{2}\\text{H}_2\\text{O} + 1\\frac{1}{2}\\text{H}_2\\text{O} \\rightarrow \\text{CaSO}_4 \\cdot 2\\text{H}_2\\text{O}\$ (gypsum). Exposure to moisture causes it to harden and lose its setting property.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Hydration is mildly exothermic, not flammable or explosive.\n• Option (C): Incorrect. It hydrates to solid gypsum; no toxic gas is released.\n• Option (D): Incorrect. Calcium metal is never produced by water exposure.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 34000),
    ),
    Question(
      id: "sci_ch2_ex14",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] What is a neutralisation reaction, and which equation correctly illustrates it?",
      options: const [
        QuestionOption(id: "A", text: "Reaction between an acid and a base to form salt and water: \$\\text{NaOH}(aq) + \\text{HCl}(aq) \\rightarrow \\text{NaCl}(aq) + \\text{H}_2\\text{O}(l)\$", isCorrect: true),
        QuestionOption(id: "B", text: "Reaction between two metals to form an alloy: \$\\text{Cu} + \\text{Zn} \\rightarrow \\text{Brass}\$", isCorrect: false),
        QuestionOption(id: "C", text: "Decomposition of water by electricity: \$2\\text{H}_2\\text{O} \\rightarrow 2\\text{H}_2 + \\text{O}_2\$", isCorrect: false),
        QuestionOption(id: "D", text: "Combustion of charcoal in oxygen: \$\\text{C} + \\text{O}_2 \\rightarrow \\text{CO}_2\$", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Reaction between an acid and a base to form salt and water: \$\\text{NaOH}(aq) + \\text{HCl}(aq) \\rightarrow \\text{NaCl}(aq) + \\text{H}_2\\text{O}(l)\$\n\nScientific Principle / Key Concept:\n\$\\text{H}^+(aq) + \\text{OH}^-(aq) \\rightarrow \\text{H}_2\\text{O}(l)\$. The acid and base neutralize each other's properties to produce neutral salt and water.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Alloy formation is a physical mixture, not an acid-base neutralisation.\n• Option (C): Incorrect. This is electrolytic decomposition.\n• Option (D): Incorrect. This is oxidation/combustion.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 35000),
    ),
    Question(
      id: "sci_ch2_ex15",
      subject: Subject.science,
      chapterId: "sci_ch_02_acids_bases_salts",
      questionText: "[EXERCISES] Which pair correctly pairs important industrial/domestic uses of washing soda and baking soda?",
      options: const [
        QuestionOption(id: "A", text: "Washing soda: glass and soap manufacture; Baking soda: constituent of baking powder and fire extinguishers", isCorrect: true),
        QuestionOption(id: "B", text: "Washing soda: dental anesthesia; Baking soda: airplane jet fuel", isCorrect: false),
        QuestionOption(id: "C", text: "Washing soda: direct consumption as food condiment; Baking soda: industrial metal welding", isCorrect: false),
        QuestionOption(id: "D", text: "Washing soda: synthesis of radioactive isotopes; Baking soda: motor vehicle engine coolant", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Washing soda: glass and soap manufacture; Baking soda: constituent of baking powder and fire extinguishers\n\nScientific Principle / Key Concept:\n\$\\text{Na}_2\\text{CO}_3\$ is used in glass, soap, paper industries and water softening; \$\\text{NaHCO}_3\$ is used in baking powder, antacids, and soda-acid extinguishers.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Neither compound serves as aircraft propellant or anesthetic.\n• Option (C): Incorrect. Washing soda is caustic and toxic if ingested.\n• Option (D): Incorrect. Fictitious uses unrelated to chemical properties.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 36000),
    ),
  ];
}
