import '../models/question.dart';

/// Pre-seeded NCERT-verified questions for NcertScienceCh5Data
class NcertScienceCh5Data {
  static List<Question> get questions => [
    Question(
      id: "sci_ch5_p81_q01",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 81)] Did Döbereiner's triads also exist in the columns of Newlands' Octaves?",
      options: const [
        QuestionOption(id: "A", text: "Yes, for example, the triad of Lithium (\$\\text{Li}\$), Sodium (\$\\text{Na}\$), and Potassium (\$\\text{K}\$) is present in the second column of Newlands' Octaves.", isCorrect: true),
        QuestionOption(id: "B", text: "No, Newlands' Octaves completely separated all three alkali metals into different periods with no vertical alignment.", isCorrect: false),
        QuestionOption(id: "C", text: "Yes, all known elements in Newlands' table formed perfect triads of three elements each.", isCorrect: false),
        QuestionOption(id: "D", text: "No, Döbereiner classified only gases whereas Newlands classified only radioactive metals.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Yes, for example, the triad of Lithium (\$\\text{Li}\$), Sodium (\$\\text{Na}\$), and Potassium (\$\\text{K}\$) is present in the second column of Newlands' Octaves.\n\nScientific Principle / Key Concept:\nComparing Döbereiner's triads and Newlands' table:\n• Döbereiner identified the triad: \$\\text{Li}\$ (atomic mass 6.9), \$\\text{Na}\$ (23.0), and \$\\text{K}\$ (39.0).\n• In Newlands' Law of Octaves, under note 're', we find the column containing \$\\text{Li}\$, followed by \$\\text{Na}\$ as the 8th element, followed by \$\\text{K}\$ as the next 8th element.\nHence, Döbereiner's alkali metal triad did indeed exist in Newlands' Octaves.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. They are in the same vertical column.\n• Option (C): Incorrect. Most other triads did not fit simultaneously.\n• Option (D): Incorrect historical facts.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 0),
    ),
    Question(
      id: "sci_ch5_p81_q02",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 81)] What was the primary limitation of Döbereiner's classification of elements into triads?",
      options: const [
        QuestionOption(id: "A", text: "He could identify only three triads (total 9 elements) from all the elements known at that time, and other elements could not be grouped into triads.", isCorrect: true),
        QuestionOption(id: "B", text: "His system required measuring atomic numbers, which had not yet been discovered.", isCorrect: false),
        QuestionOption(id: "C", text: "All triads formed by Döbereiner decomposed into radioactive isotopes upon heating.", isCorrect: false),
        QuestionOption(id: "D", text: "The atomic mass of the middle element was always exactly zero.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) He could identify only three triads (total 9 elements) from all the elements known at that time, and other elements could not be grouped into triads.\n\nScientific Principle / Key Concept:\n• Döbereiner stated that when elements are arranged in increasing order of atomic masses in groups of three (triads), the atomic mass of the middle element is roughly the average of the other two.\n• Limitation: Döbereiner could identify only three such triads from the elements known at that time:\n  1. \$\\text{Li}, \\text{Na}, \\text{K}\$\n  2. \$\\text{Ca}, \\text{Sr}, \\text{Ba}\$\n  3. \$\\text{Cl}, \\text{Br}, \\text{I}\$\nHe failed to classify all the remaining elements into triads, rendering the system incomplete and not practically useful.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Atomic number was introduced by Moseley in 1913.\n• Option (C): Incorrect. Non-radioactive elements were used.\n• Option (D): Nonsensical statement.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 1000),
    ),
    Question(
      id: "sci_ch5_p81_q03",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 81)] Which of the following describes the key limitations of Newlands' Law of Octaves?",
      options: const [
        QuestionOption(id: "A", text: "It was applicable only up to calcium (elements beyond calcium did not show octave periodicity), assumed only 56 elements existed, and forced unlike elements into the same slot (e.g., Co and Ni with halogens F, Cl, Br).", isCorrect: true),
        QuestionOption(id: "B", text: "It applied exclusively to heavy radioactive elements and ignored all lighter elements like hydrogen and lithium.", isCorrect: false),
        QuestionOption(id: "C", text: "It arranged elements strictly in descending order of atomic volumes with no musical analogy.", isCorrect: false),
        QuestionOption(id: "D", text: "It successfully predicted the existence and properties of noble gases before they were discovered.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) It was applicable only up to calcium (elements beyond calcium did not show octave periodicity), assumed only 56 elements existed, and forced unlike elements into the same slot (e.g., Co and Ni with halogens F, Cl, Br).\n\nScientific Principle / Key Concept:\nLimitations of Newlands' Law of Octaves:\n1. Applicable only up to Calcium: After calcium, every eighth element did not possess properties similar to the first element.\n2. Inflexible assumption: Newlands assumed that only 56 elements existed in nature and no more elements would ever be discovered.\n3. Fitting inconsistencies: To fit existing elements into his table, Newlands adjusted two elements in the same slot (e.g., Cobalt and Nickel) and placed them in the same column as Fluorine, Chlorine, and Bromine, which have totally different properties. Furthermore, Iron (which resembles Co and Ni) was placed far away.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. It worked only for light elements.\n• Option (C): Incorrect. It used increasing atomic mass and musical octaves.\n• Option (D): Incorrect. Noble gases disrupted the octave law.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 2000),
    ),
    Question(
      id: "sci_ch5_p85_q01",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 85)] Using Mendeléev's Periodic Table group oxide formulas, what are the predicted formulae for the oxides of Potassium (\$\\text{K}\$), Carbon (\$\\text{C}\$), Aluminium (\$\\text{Al}\$), Silicon (\$\\text{Si}\$), and Barium (\$\\text{Ba}\$)?",
      options: const [
        QuestionOption(id: "A", text: "\$\\text{K}_2\\text{O}\$ (Group I, \$\\text{R}_2\\text{O}\$), \$\\text{CO}_2\$ (Group IV, \$\\text{RO}_2\$), \$\\text{Al}_2\\text{O}_3\$ (Group III, \$\\text{R}_2\\text{O}_3\$), \$\\text{SiO}_2\$ (Group IV, \$\\text{RO}_2\$), and \$\\text{BaO}\$ (Group II, \$\\text{RO}\$).", isCorrect: true),
        QuestionOption(id: "B", text: "\$\\text{KO}_2, \\text{CO}, \\text{AlO}, \\text{SiO}, \\text{Ba}_2\\text{O}\$", isCorrect: false),
        QuestionOption(id: "C", text: "\$\\text{K}_2\\text{O}_2, \\text{C}_2\\text{O}_4, \\text{Al}_3\\text{O}_2, \\text{Si}_2\\text{O}, \\text{BaO}_2\$", isCorrect: false),
        QuestionOption(id: "D", text: "All five elements form identical monoxide compounds: \$\\text{KO}, \\text{CO}, \\text{AlO}, \\text{SiO}, \\text{BaO}\$.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) \$\\text{K}_2\\text{O}\$ (Group I, \$\\text{R}_2\\text{O}\$), \$\\text{CO}_2\$ (Group IV, \$\\text{RO}_2\$), \$\\text{Al}_2\\text{O}_3\$ (Group III, \$\\text{R}_2\\text{O}_3\$), \$\\text{SiO}_2\$ (Group IV, \$\\text{RO}_2\$), and \$\\text{BaO}\$ (Group II, \$\\text{RO}\$).\n\nScientific Principle / Key Concept:\nIn Mendeléev's Periodic Table, the general formulae of oxides at the top of the groups are:\n• Group I (General oxide \$\\text{R}_2\\text{O}\$): \$\\text{K} \\rightarrow \\text{K}_2\\text{O}\$\n• Group II (General oxide \$\\text{RO}\$): \$\\text{Ba} \\rightarrow \\text{BaO}\$\n• Group III (General oxide \$\\text{R}_2\\text{O}_3\$): \$\\text{Al} \\rightarrow \\text{Al}_2\\text{O}_3\$\n• Group IV (General oxide \$\\text{RO}_2\$): \$\\text{C} \\rightarrow \\text{CO}_2\$ and \$\\text{Si} \\rightarrow \\text{SiO}_2\$\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect valencies.\n• Option (C): Peroxide/unsimplified formulae.\n• Option (D): Ignores group valency differences.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 3000),
    ),
    Question(
      id: "sci_ch5_p85_q02",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 85)] Besides gallium (which replaced Eka-aluminium), which other elements were predicted by Mendeléev and discovered later?",
      options: const [
        QuestionOption(id: "A", text: "Scandium (which replaced Eka-boron) and Germanium (which replaced Eka-silicon).", isCorrect: true),
        QuestionOption(id: "B", text: "Sodium and Potassium.", isCorrect: false),
        QuestionOption(id: "C", text: "Helium and Argon.", isCorrect: false),
        QuestionOption(id: "D", text: "Iron and Cobalt.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Scandium (which replaced Eka-boron) and Germanium (which replaced Eka-silicon).\n\nScientific Principle / Key Concept:\nMendeléev predicted the existence of elements that were undiscovered at his time by leaving gaps in his table. He named them by prefixing Sanskrit 'Eka' (meaning 'one') to the preceding element in the same group:\n1. Eka-boron \$\\rightarrow\$ Scandium (\$\\text{Sc}\$)\n2. Eka-aluminium \$\\rightarrow\$ Gallium (\$\\text{Ga}\$)\n3. Eka-silicon \$\\rightarrow\$ Germanium (\$\\text{Ge}\$)\nWhen these elements were subsequently discovered, their actual atomic masses and properties matched Mendeléev's predictions with remarkable accuracy.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Known ancient/early elements.\n• Option (C): Noble gases were discovered later, but were not Eka-elements.\n• Option (D): Classical elements.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 4000),
    ),
    Question(
      id: "sci_ch5_p85_q03",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 85)] What were the primary scientific criteria used by Mendeléev in creating his Periodic Table?",
      options: const [
        QuestionOption(id: "A", text: "Arrangement in order of increasing atomic masses, combined with similarity in chemical properties (specifically the formulae of hydrides and oxides formed by the elements).", isCorrect: true),
        QuestionOption(id: "B", text: "Strict arrangement according to atomic numbers and electron spin quantum numbers.", isCorrect: false),
        QuestionOption(id: "C", text: "Alphabetical sorting of element names based on Russian phonetic symbols.", isCorrect: false),
        QuestionOption(id: "D", text: "Density of metals at room temperature and thermal boiling points alone.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Arrangement in order of increasing atomic masses, combined with similarity in chemical properties (specifically the formulae of hydrides and oxides formed by the elements).\n\nScientific Principle / Key Concept:\nMendeléev's Periodic Law: 'The properties of elements are the periodic function of their atomic masses.'\nCriteria used:\n1. Increasing order of atomic masses.\n2. Chemical properties: He focused particularly on compounds formed by elements with hydrogen and oxygen (hydrides and oxides), as these two elements are highly reactive and form compounds with nearly all elements. The formulae of hydrides and oxides served as fundamental criteria for grouping.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Atomic number was introduced by Moseley in 1913.\n• Option (C): Incorrect. Scientific, not linguistic basis.\n• Option (D): Incorrect. Density was secondary.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 5000),
    ),
    Question(
      id: "sci_ch5_p85_q04",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 85)] Why are noble gases (helium, neon, argon) placed in a separate group in the Periodic Table?",
      options: const [
        QuestionOption(id: "A", text: "They are chemically inert with completely filled valence electron shells (zero valency), distinct from reactive elements, and placing them in a separate group does not disturb the existing classification.", isCorrect: true),
        QuestionOption(id: "B", text: "They are radioactive liquids that dissolve all known glassware.", isCorrect: false),
        QuestionOption(id: "C", text: "They have infinite atomic mass and cannot be weighed by mass spectrometers.", isCorrect: false),
        QuestionOption(id: "D", text: "They react violently with halogens to produce explosive acidic solids.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) They are chemically inert with completely filled valence electron shells (zero valency), distinct from reactive elements, and placing them in a separate group does not disturb the existing classification.\n\nScientific Principle / Key Concept:\n• Noble gases (Helium, Neon, Argon, Krypton, Xenon) have completely filled outermost electronic shells (He: \$2\$; Ne: \$2,8\$; Ar: \$2,8,8\$).\n• Because of this stable electronic configuration, they show zero valency and extreme chemical inertness.\n• They occur in very low concentrations in the atmosphere and were discovered late.\n• Because all noble gases share identical chemical inertness and zero valency, placing them in a separate dedicated group (Group 18 / Group 0) accommodates them naturally without disturbing the arrangement of the other elements.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. They are inert gases.\n• Option (C): Incorrect. They have normal atomic masses.\n• Option (D): Incorrect. They do not react under standard conditions.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 6000),
    ),
    Question(
      id: "sci_ch5_p90_q01",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 90)] How did the Modern Periodic Table resolve the major anomalies of Mendeléev's Periodic Table?",
      options: const [
        QuestionOption(id: "A", text: "By adopting atomic number (\$Z\$) instead of atomic mass as the organizing principle, naturally accommodating isotopes in the same position and resolving anomalous mass pairs like Cobalt (\$Z=27\$) before Nickel (\$Z=28\$).", isCorrect: true),
        QuestionOption(id: "B", text: "By eliminating all metals and keeping only gaseous non-metals.", isCorrect: false),
        QuestionOption(id: "C", text: "By arranging elements in alphabetical order of their Latin names.", isCorrect: false),
        QuestionOption(id: "D", text: "By placing isotopes in completely separate periods across the table.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) By adopting atomic number (\$Z\$) instead of atomic mass as the organizing principle, naturally accommodating isotopes in the same position and resolving anomalous mass pairs like Cobalt (\$Z=27\$) before Nickel (\$Z=28\$).\n\nScientific Principle / Key Concept:\nHenry Moseley (1913) demonstrated that atomic number (\$Z\$, number of protons) is a more fundamental property than atomic mass. Modern Periodic Law states: 'Properties of elements are a periodic function of their atomic numbers.'\nHow anomalies were resolved:\n1. Position of Isotopes: Isotopes have identical atomic numbers. Hence, they naturally share the exact same slot in the Modern Periodic Table.\n2. Anomalous Pairs: Cobalt (\$Z=27\$) comes before Nickel (\$Z=28\$), resolving Mendeléev's inverted mass anomaly (mass of Co = 58.9, Ni = 58.7).\n3. Prediction of elements: Atomic numbers increase by integers (\$1, 2, 3...\$), making it possible to predict exactly how many undiscovered elements exist between two elements.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. All elements are included.\n• Option (C): Incorrect. It uses atomic number, not alphabet.\n• Option (D): Incorrect. Isotopes occupy the same slot.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 7000),
    ),
    Question(
      id: "sci_ch5_p90_q02",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 90)] Name two elements you would expect to show chemical reactions similar to Magnesium (\$\\text{Mg}\$, \$Z=12\$). What is the basis for your choice?",
      options: const [
        QuestionOption(id: "A", text: "Beryllium (\$\\text{Be}\$) and Calcium (\$\\text{Ca}\$); basis: they belong to the same group (Group 2, alkaline earth metals) and have the same number of valence electrons (2).", isCorrect: true),
        QuestionOption(id: "B", text: "Sodium (\$\\text{Na}\$) and Aluminium (\$\\text{Al}\$); basis: they are adjacent in the same horizontal period.", isCorrect: false),
        QuestionOption(id: "C", text: "Carbon (\$\\text{C}\$) and Silicon (\$\\text{Si}\$); basis: they form four covalent bonds.", isCorrect: false),
        QuestionOption(id: "D", text: "Fluorine (\$\\text{F}\$) and Chlorine (\$\\text{Cl}\$); basis: they are gaseous halogens.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Beryllium (\$\\text{Be}\$) and Calcium (\$\\text{Ca}\$); basis: they belong to the same group (Group 2, alkaline earth metals) and have the same number of valence electrons (2).\n\nScientific Principle / Key Concept:\n• Chemical properties of elements are determined by the number of valence electrons.\n• Magnesium (\$Z=12\$) has electronic configuration \$2, 8, 2\$ (2 valence electrons, Group 2).\n• Beryllium (\$Z=4\$, configuration \$2, 2\$) and Calcium (\$Z=20\$, configuration \$2, 8, 8, 2\$) also have 2 valence electrons and belong to Group 2.\n• Because they possess the same valence electron count, they exhibit similar chemical reactivity (e.g., forming divalent basic oxides \$\\text{BeO}, \\text{CaO}, \\text{MgO}\$ and reacting with acids to liberate \$\\text{H}_2\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Period neighbors have different chemical valencies.\n• Option (C): Incorrect. C and Si are Group 14.\n• Option (D): Incorrect. Halogens are Group 17.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 8000),
    ),
    Question(
      id: "sci_ch5_p90_q03_a",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 90)] Name three elements that have a single electron in their outermost shells.",
      options: const [
        QuestionOption(id: "A", text: "Lithium (\$\\text{Li}\$), Sodium (\$\\text{Na}\$), and Potassium (\$\\text{K}\$)", isCorrect: true),
        QuestionOption(id: "B", text: "Magnesium (\$\\text{Mg}\$), Calcium (\$\\text{Ca}\$), and Barium (\$\\text{Ba}\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Helium (\$\\text{He}\$), Neon (\$\\text{Ne}\$), and Argon (\$\\text{Ar}\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Fluorine (\$\\text{F}\$), Chlorine (\$\\text{Cl}\$), and Bromine (\$\\text{Br}\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Lithium (\$\\text{Li}\$), Sodium (\$\\text{Na}\$), and Potassium (\$\\text{K}\$)\n\nScientific Principle / Key Concept:\nAlkali metals belong to Group 1 of the Modern Periodic Table and have 1 valence electron in their outermost shell:\n• \$\\text{Li} (Z=3): 2, 1\$\n• \$\\text{Na} (Z=11): 2, 8, 1\$\n• \$\\text{K} (Z=19): 2, 8, 8, 1\$\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Group 2 elements have 2 valence electrons.\n• Option (C): Noble gases have 8 (or 2 for He) valence electrons.\n• Option (D): Halogens have 7 valence electrons.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 9000),
    ),
    Question(
      id: "sci_ch5_p90_q03_b",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 90)] Name two elements that have two electrons in their outermost shells.",
      options: const [
        QuestionOption(id: "A", text: "Magnesium (\$\\text{Mg}\$) and Calcium (\$\\text{Ca}\$)", isCorrect: true),
        QuestionOption(id: "B", text: "Carbon (\$\\text{C}\$) and Silicon (\$\\text{Si}\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Lithium (\$\\text{Li}\$) and Sodium (\$\\text{Na}\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Oxygen (\$\\text{O}\$) and Sulphur (\$\\text{S}\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Magnesium (\$\\text{Mg}\$) and Calcium (\$\\text{Ca}\$)\n\nScientific Principle / Key Concept:\nAlkaline earth metals (Group 2) have 2 electrons in their outermost shell:\n• Magnesium (\$Z=12\$): \$2, 8, 2\$\n• Calcium (\$Z=20\$): \$2, 8, 8, 2\$\n(Also Beryllium: \$2, 2\$; Strontium: \$2, 8, 18, 8, 2\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Group 14 elements have 4 valence electrons.\n• Option (C): Group 1 elements have 1 valence electron.\n• Option (D): Group 16 elements have 6 valence electrons.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 10000),
    ),
    Question(
      id: "sci_ch5_p90_q03_c",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 90)] Name three elements with completely filled outermost shells.",
      options: const [
        QuestionOption(id: "A", text: "Helium (\$\\text{He}\$), Neon (\$\\text{Ne}\$), and Argon (\$\\text{Ar}\$)", isCorrect: true),
        QuestionOption(id: "B", text: "Chlorine (\$\\text{Cl}\$), Bromine (\$\\text{Br}\$), and Iodine (\$\\text{I}\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Sodium (\$\\text{Na}\$), Potassium (\$\\text{K}\$), and Rubidium (\$\\text{Rb}\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Nitrogen (\$\\text{N}\$), Phosphorus (\$\\text{P}\$), and Arsenic (\$\\text{As}\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Helium (\$\\text{He}\$), Neon (\$\\text{Ne}\$), and Argon (\$\\text{Ar}\$)\n\nScientific Principle / Key Concept:\nNoble gases (Group 18) have completely filled outermost shells:\n• Helium (\$Z=2\$): Electronic configuration \$2\$ (K shell completely filled).\n• Neon (\$Z=10\$): Electronic configuration \$2, 8\$ (L shell completely filled).\n• Argon (\$Z=18\$): Electronic configuration \$2, 8, 8\$ (M shell has complete octet).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Halogens need 1 electron.\n• Option (C): Alkali metals have 1 valence electron.\n• Option (D): Pnictogens have 5 valence electrons.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 11000),
    ),
    Question(
      id: "sci_ch5_p90_q04_a",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 90)] Lithium, sodium, and potassium are all metals that react with water to liberate hydrogen gas. What fundamental similarity exists in the atoms of these elements?",
      options: const [
        QuestionOption(id: "A", text: "All of them have exactly 1 valence electron in their outermost shell, which they readily lose to form univalent cations (\$\\text{M}^+\$).", isCorrect: true),
        QuestionOption(id: "B", text: "They have the exact same number of occupied electron shells.", isCorrect: false),
        QuestionOption(id: "C", text: "They all have completely filled outermost octets like noble gases.", isCorrect: false),
        QuestionOption(id: "D", text: "They possess identical atomic masses and nuclear proton counts.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) All of them have exactly 1 valence electron in their outermost shell, which they readily lose to form univalent cations (\$\\text{M}^+\$).\n\nScientific Principle / Key Concept:\n• Lithium (\$Z=3\$): \$2, 1\$\n• Sodium (\$Z=11\$): \$2, 8, 1\$\n• Potassium (\$Z=19\$): \$2, 8, 8, 1\$\nSimilarity: All three elements have 1 electron in their valence shell. Because they have the same valence electronic configuration, they lose this single electron with ease to attain a noble gas structure, reacting vigorously with water to form basic hydroxides and hydrogen gas:\n\$\$2\\text{M}(s) + 2\\text{H}_2\\text{O}(l) \\rightarrow 2\\text{MOH}(aq) + \\text{H}_2(g)\$\$\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Number of shells increases: 2, 3, 4.\n• Option (C): Incorrect. They have 1 electron in their outer shell.\n• Option (D): Incorrect. They have different atomic masses.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 12000),
    ),
    Question(
      id: "sci_ch5_p90_q04_b",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 90)] Helium is an unreactive gas and neon is a gas of extremely low reactivity. What do their atoms have in common?",
      options: const [
        QuestionOption(id: "A", text: "Both have completely filled outermost valence shells (He has a filled duplet in the K shell; Ne has a filled octet in the L shell), conferring zero chemical valency.", isCorrect: true),
        QuestionOption(id: "B", text: "Both have exactly 8 electrons in their outermost valence shell.", isCorrect: false),
        QuestionOption(id: "C", text: "Both have 2 occupied electron shells.", isCorrect: false),
        QuestionOption(id: "D", text: "Both readily form diatomic molecules \$\\text{He}_2\$ and \$\\text{Ne}_2\$ in air.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Both have completely filled outermost valence shells (He has a filled duplet in the K shell; Ne has a filled octet in the L shell), conferring zero chemical valency.\n\nScientific Principle / Key Concept:\n• Helium (\$Z=2\$): Electronic configuration is \$2\$. Its outermost K shell can hold a maximum of 2 electrons (\$2n^2 = 2(1)^2 = 2\$). Thus, its outermost shell is completely filled (stable duplet).\n• Neon (\$Z=10\$): Electronic configuration is \$2, 8\$. Its outermost L shell is completely filled with 8 electrons (stable octet).\n• Common feature: Both atoms have completely filled outermost shells, which gives them maximum stability and zero valency, explaining their chemical unreactivity.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. He has 2, not 8 valence electrons.\n• Option (C): Incorrect. He has 1 shell; Ne has 2 shells.\n• Option (D): Incorrect. Noble gases are monoatomic.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 13000),
    ),
    Question(
      id: "sci_ch5_p90_q05",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 90)] In the Modern Periodic Table, which elements among the first ten elements (atomic numbers 1 to 10) are metals?",
      options: const [
        QuestionOption(id: "A", text: "Lithium (\$\\text{Li}\$, \$Z=3\$) and Beryllium (\$\\text{Be}\$, \$Z=4\$)", isCorrect: true),
        QuestionOption(id: "B", text: "Boron (\$\\text{B}\$) and Carbon (\$\\text{C}\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Hydrogen (\$\\text{H}\$) and Helium (\$\\text{He}\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Sodium (\$\\text{Na}\$) and Magnesium (\$\\text{Mg}\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Lithium (\$\\text{Li}\$, \$Z=3\$) and Beryllium (\$\\text{Be}\$, \$Z=4\$)\n\nScientific Principle / Key Concept:\nThe first ten elements are:\n1. \$\\text{H}\$ (Hydrogen) - Non-metal\n2. \$\\text{He}\$ (Helium) - Non-metal (noble gas)\n3. \$\\text{Li}\$ (Lithium) - Metal (Alkali metal)\n4. \$\\text{Be}\$ (Beryllium) - Metal (Alkaline earth metal)\n5. \$\\text{B}\$ (Boron) - Metalloid\n6. \$\\text{C}\$ (Carbon) - Non-metal\n7. \$\\text{N}\$ (Nitrogen) - Non-metal\n8. \$\\text{O}\$ (Oxygen) - Non-metal\n9. \$\\text{F}\$ (Fluorine) - Non-metal (halogen)\n10. \$\\text{Ne}\$ (Neon) - Non-metal (noble gas)\nHence, only Lithium (\$\\text{Li}\$) and Beryllium (\$\\text{Be}\$) are metals.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Boron is a metalloid and carbon is a non-metal.\n• Option (C): H and He are non-metals.\n• Option (D): Na and Mg have \$Z=11\$ and \$12\$, exceeding 10.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 14000),
    ),
    Question(
      id: "sci_ch5_p90_q06",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[QUESTIONS (Page 90)] By considering their positions in the Periodic Table, which of the following elements would you expect to have the maximum metallic characteristic: \$\\text{Ga}\$, \$\\text{Ge}\$, \$\\text{As}\$, \$\\text{Se}\$, or \$\\text{Be}\$?",
      options: const [
        QuestionOption(id: "A", text: "Beryllium (\$\\text{Be}\$)", isCorrect: true),
        QuestionOption(id: "B", text: "Selenium (\$\\text{Se}\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Arsenic (\$\\text{As}\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Germanium (\$\\text{Ge}\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Beryllium (\$\\text{Be}\$)\n\nScientific Principle / Key Concept:\n• Positions in Periodic Table:\n  - \$\\text{Be}\$: Group 2, Period 2\n  - \$\\text{Ga}\$: Group 13, Period 4\n  - \$\\text{Ge}\$: Group 14, Period 4\n  - \$\\text{As}\$: Group 15, Period 4\n  - \$\\text{Se}\$: Group 16, Period 4\n• Trends in Metallic Character:\n  1. Across a period (left to right): Metallic character decreases as effective nuclear charge increases.\n     In Period 4: \$\\text{Ga} > \\text{Ge} > \\text{As} > \\text{Se}\$.\n  2. Comparing \$\\text{Be}\$ and \$\\text{Ga}\$:\n     \$\\text{Be}\$ is in Group 2 (alkaline earth metal), situated further to the left than Group 13 (\$\\text{Ga}\$). Group 2 elements are electropositive metals, whereas Group 13 elements possess higher electronegativity and amphoteric character. Hence, Beryllium has the maximum metallic characteristic among the given choices.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Se is a non-metal.\n• Option (C): As is a metalloid.\n• Option (D): Ge is a metalloid.",
      difficultyLevel: DifficultyLevel.hots,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 15000),
    ),
    Question(
      id: "sci_ch5_ex_q01",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 1] Which of the following statements is NOT a correct statement about the trends when going from left to right across the periods of the Periodic Table?",
      options: const [
        QuestionOption(id: "A", text: "The atoms lose their electrons more easily.", isCorrect: true),
        QuestionOption(id: "B", text: "The elements become less metallic in nature.", isCorrect: false),
        QuestionOption(id: "C", text: "The number of valence electrons increases.", isCorrect: false),
        QuestionOption(id: "D", text: "The oxides become more acidic.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The atoms lose their electrons more easily.\n\nScientific Principle / Key Concept:\nMoving from left to right across a period:\n1. Valence electrons increase from 1 to 8.\n2. Effective nuclear charge increases as protons are added to the nucleus while electrons enter the same shell.\n3. Atomic radius decreases, holding valence electrons more tightly.\n4. Therefore, ionization enthalpy increases, meaning atoms lose electrons with greater difficulty (less easily).\n5. Consequently, metallic character decreases and oxides become more acidic.\nThus, statement (c) / option (A) is INCORRECT.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): True statement (metallic character decreases).\n• Option (C): True statement (valence electrons increase from 1 to 8).\n• Option (D): True statement (oxides transition from basic to acidic).",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 16000),
    ),
    Question(
      id: "sci_ch5_ex_q02",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 2] Element X forms a chloride with the formula \$\\text{XCl}_2\$, which is a solid with a high melting point. X would most likely be in the same group of the Periodic Table as:",
      options: const [
        QuestionOption(id: "A", text: "Magnesium (\$\\text{Mg}\$)", isCorrect: true),
        QuestionOption(id: "B", text: "Sodium (\$\\text{Na}\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Aluminium (\$\\text{Al}\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Silicon (\$\\text{Si}\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Magnesium (\$\\text{Mg}\$)\n\nScientific Principle / Key Concept:\n• The chemical formula \$\\text{XCl}_2\$ shows that element X has a combining capacity (valency) of 2.\n• A solid with a high melting point indicates an ionic compound.\n• Among the given options:\n  - \$\\text{Na}\$ (Group 1): Valency = 1 \$\\rightarrow \\text{NaCl}\$\n  - \$\\text{Mg}\$ (Group 2): Valency = 2 \$\\rightarrow \\text{MgCl}_2\$ (ionic solid, high MP)\n  - \$\\text{Al}\$ (Group 13): Valency = 3 \$\\rightarrow \\text{AlCl}_3\$\n  - \$\\text{Si}\$ (Group 14): Valency = 4 \$\\rightarrow \\text{SiCl}_4\$\nTherefore, X belongs to Group 2, the same group as Magnesium (\$\\text{Mg}\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Na forms \$\\text{NaCl}\$.\n• Option (C): Al forms \$\\text{AlCl}_3\$.\n• Option (D): Si forms \$\\text{SiCl}_4\$.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 17000),
    ),
    Question(
      id: "sci_ch5_ex_q03_a",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 3(a)] Which element has two shells, both of which are completely filled with electrons?",
      options: const [
        QuestionOption(id: "A", text: "Neon (\$\\text{Ne}\$, \$Z=10\$), with electronic configuration \$2, 8\$", isCorrect: true),
        QuestionOption(id: "B", text: "Argon (\$\\text{Ar}\$, \$Z=18\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Helium (\$\\text{He}\$, \$Z=2\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Fluorine (\$\\text{F}\$, \$Z=9\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Neon (\$\\text{Ne}\$, \$Z=10\$), with electronic configuration \$2, 8\$\n\nScientific Principle / Key Concept:\n• The maximum capacity of K shell (\$n=1\$) is \$2(1)^2 = 2\$ electrons.\n• The maximum capacity of L shell (\$n=2\$) is \$2(2)^2 = 8\$ electrons.\n• An element with both shells completely filled has electronic configuration \$2, 8\$.\n• Total electrons = \$2 + 8 = 10\$, which corresponds to Neon (\$\\text{Ne}\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Ar has 3 shells (\$2, 8, 8\$).\n• Option (C): He has only 1 shell (\$2\$).\n• Option (D): F has \$2, 7\$ (unfilled second shell).",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 18000),
    ),
    Question(
      id: "sci_ch5_ex_q03_b",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 3(b)] Which element has the electronic configuration \$2, 8, 2\$?",
      options: const [
        QuestionOption(id: "A", text: "Magnesium (\$\\text{Mg}\$, \$Z=12\$)", isCorrect: true),
        QuestionOption(id: "B", text: "Calcium (\$\\text{Ca}\$, \$Z=20\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Sodium (\$\\text{Na}\$, \$Z=11\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Aluminium (\$\\text{Al}\$, \$Z=13\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Magnesium (\$\\text{Mg}\$, \$Z=12\$)\n\nScientific Principle / Key Concept:\n• Given configuration: \$2, 8, 2\$.\n• Total number of electrons = \$2 + 8 + 2 = 12\$.\n• For a neutral atom, atomic number \$Z = 12\$, which is Magnesium (\$\\text{Mg}\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Ca is \$Z=20\$ (\$2,8,8,2\$).\n• Option (C): Na is \$Z=11\$ (\$2,8,1\$).\n• Option (D): Al is \$Z=13\$ (\$2,8,3\$).",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 19000),
    ),
    Question(
      id: "sci_ch5_ex_q03_c",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 3(c)] Which element has a total of three shells, with four electrons in its valence shell?",
      options: const [
        QuestionOption(id: "A", text: "Silicon (\$\\text{Si}\$, \$Z=14\$), with electronic configuration \$2, 8, 4\$", isCorrect: true),
        QuestionOption(id: "B", text: "Carbon (\$\\text{C}\$, \$Z=6\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Germanium (\$\\text{Ge}\$, \$Z=32\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Phosphorus (\$\\text{P}\$, \$Z=15\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Silicon (\$\\text{Si}\$, \$Z=14\$), with electronic configuration \$2, 8, 4\$\n\nScientific Principle / Key Concept:\n• Three shells (K, L, M) means K=2, L=8, and M shell has 4 valence electrons.\n• Electronic configuration: \$2, 8, 4\$.\n• Total number of electrons = \$2 + 8 + 4 = 14\$.\n• Atomic number 14 belongs to Silicon (\$\\text{Si}\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Carbon has 2 shells (\$2, 4\$).\n• Option (C): Germanium has 4 shells.\n• Option (D): Phosphorus has 5 valence electrons.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 20000),
    ),
    Question(
      id: "sci_ch5_ex_q03_d",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 3(d)] Which element has a total of two shells, with three electrons in its valence shell?",
      options: const [
        QuestionOption(id: "A", text: "Boron (\$\\text{B}\$, \$Z=5\$), with electronic configuration \$2, 3\$", isCorrect: true),
        QuestionOption(id: "B", text: "Aluminium (\$\\text{Al}\$, \$Z=13\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Lithium (\$\\text{Li}\$, \$Z=3\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Nitrogen (\$\\text{N}\$, \$Z=7\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Boron (\$\\text{B}\$, \$Z=5\$), with electronic configuration \$2, 3\$\n\nScientific Principle / Key Concept:\n• Two shells (K and L) with 3 valence electrons in L shell.\n• Electronic configuration: \$2, 3\$.\n• Total number of electrons = \$2 + 3 = 5\$.\n• Atomic number 5 corresponds to Boron (\$\\text{B}\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Aluminium has 3 shells (\$2, 8, 3\$).\n• Option (C): Lithium has 1 valence electron (\$2, 1\$).\n• Option (D): Nitrogen has 5 valence electrons (\$2, 5\$).",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 21000),
    ),
    Question(
      id: "sci_ch5_ex_q03_e",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 3(e)] Which element has twice as many electrons in its second shell as in its first shell?",
      options: const [
        QuestionOption(id: "A", text: "Carbon (\$\\text{C}\$, \$Z=6\$), with electronic configuration \$2, 4\$", isCorrect: true),
        QuestionOption(id: "B", text: "Beryllium (\$\\text{Be}\$, \$Z=4\$)", isCorrect: false),
        QuestionOption(id: "C", text: "Oxygen (\$\\text{O}\$, \$Z=8\$)", isCorrect: false),
        QuestionOption(id: "D", text: "Magnesium (\$\\text{Mg}\$, \$Z=12\$)", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Carbon (\$\\text{C}\$, \$Z=6\$), with electronic configuration \$2, 4\$\n\nScientific Principle / Key Concept:\n• The first shell (K) can accommodate maximum 2 electrons.\n• Second shell (L) has twice as many electrons = \$2 \\times 2 = 4\$ electrons.\n• Configuration is \$2, 4\$.\n• Total number of electrons = \$2 + 4 = 6\$.\n• Atomic number 6 corresponds to Carbon (\$\\text{C}\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Be is \$2, 2\$ (1:1 ratio).\n• Option (C): O is \$2, 6\$ (3:1 ratio).\n• Option (D): Mg has 3 shells.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 22000),
    ),
    Question(
      id: "sci_ch5_ex_q04_a",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 4(a)] What property do all elements in the same column (Group 13) of the Periodic Table as boron have in common?",
      options: const [
        QuestionOption(id: "A", text: "All of them have 3 valence electrons in their outermost shell and exhibit a common chemical valency of 3.", isCorrect: true),
        QuestionOption(id: "B", text: "All of them are non-metallic gases at room temperature.", isCorrect: false),
        QuestionOption(id: "C", text: "All of them have completely filled outermost octets.", isCorrect: false),
        QuestionOption(id: "D", text: "All of them form singly charged \$\\text{M}^+\$ univalent cations exclusively.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) All of them have 3 valence electrons in their outermost shell and exhibit a common chemical valency of 3.\n\nScientific Principle / Key Concept:\n• All elements in the same column (Group 13) as Boron (\$\\text{B}, \\text{Al}, \\text{Ga}, \\text{In}, \\text{Tl}\$) possess 3 electrons in their valence shell (\$ns^2 np^1\$).\n• Consequently, they share a common valency of 3 and form oxides with general formula \$\\text{R}_2\\text{O}_3\$ and halides with formula \$\\text{RCl}_3\$.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. They are solids; only B is a metalloid, others are metals.\n• Option (C): Incorrect. They have 3 valence electrons.\n• Option (D): Group 1 alkali metals form \$\\text{M}^+\$.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 23000),
    ),
    Question(
      id: "sci_ch5_ex_q04_b",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 4(b)] What property do all elements in the same column (Group 17) of the Periodic Table as fluorine have in common?",
      options: const [
        QuestionOption(id: "A", text: "All of them have 7 valence electrons in their outermost shell, a valency of 1, and strong tendency to gain 1 electron forming univalent halide anions (\$\\text{X}^-\$).", isCorrect: true),
        QuestionOption(id: "B", text: "All of them are strongly electropositive metals that lose 7 electrons.", isCorrect: false),
        QuestionOption(id: "C", text: "All of them form basic metal oxides with water.", isCorrect: false),
        QuestionOption(id: "D", text: "All of them have completely filled outermost shells with zero valency.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) All of them have 7 valence electrons in their outermost shell, a valency of 1, and strong tendency to gain 1 electron forming univalent halide anions (\$\\text{X}^-\$).\n\nScientific Principle / Key Concept:\n• All elements in Group 17 (Halogens: \$\\text{F}, \\text{Cl}, \\text{Br}, \\text{I}, \\text{At}\$) have 7 electrons in their outermost shell (\$ns^2 np^5\$).\n• They all need 1 electron to achieve stable octet configuration.\n• Hence, they all share a common valency of 1 (\$8 - 7 = 1\$) and form univalent anions (\$\\text{F}^-, \\text{Cl}^-, \\text{Br}^-, \\text{I}^-\$).\n• They all form diatomic molecules (\$\\text{F}_2, \\text{Cl}_2, \\text{Br}_2, \\text{I}_2\$) and salts with metals.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. They are electronegative non-metals.\n• Option (C): Incorrect. Non-metal oxides are acidic.\n• Option (D): Incorrect. They have 7, not 8 valence electrons.",
      difficultyLevel: DifficultyLevel.easy,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 24000),
    ),
    Question(
      id: "sci_ch5_ex_q05",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 5] An atom has electronic configuration \$2, 8, 7\$. What is the atomic number of this element, and to which of the following elements would it be chemically similar: \$\\text{N}(7), \\text{F}(9), \\text{P}(15), \\text{Ar}(18)\$?",
      options: const [
        QuestionOption(id: "A", text: "Atomic number = 17 (Chlorine); chemically similar to Fluorine (\$\\text{F}\$, \$Z=9\$) because both have 7 valence electrons in their outermost shell.", isCorrect: true),
        QuestionOption(id: "B", text: "Atomic number = 18; chemically similar to Argon (\$\\text{Ar}\$, \$Z=18\$).", isCorrect: false),
        QuestionOption(id: "C", text: "Atomic number = 17; chemically similar to Nitrogen (\$\\text{N}\$, \$Z=7\$).", isCorrect: false),
        QuestionOption(id: "D", text: "Atomic number = 15; chemically similar to Phosphorus (\$\\text{P}\$, \$Z=15\$).", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Atomic number = 17 (Chlorine); chemically similar to Fluorine (\$\\text{F}\$, \$Z=9\$) because both have 7 valence electrons in their outermost shell.\n\nScientific Principle / Key Concept:\n1. Atomic number = total number of electrons = \$2 + 8 + 7 = 17\$ (Chlorine, \$\\text{Cl}\$).\n2. Chemical similarity depends on the number of valence electrons:\n• \$\\text{N} (Z=7): 2, 5\$ (5 valence electrons)\n• \$\\text{F} (Z=9): 2, 7\$ (7 valence electrons)\n• \$\\text{P} (Z=15): 2, 8, 5\$ (5 valence electrons)\n• \$\\text{Ar} (Z=18): 2, 8, 8\$ (8 valence electrons)\nSince Fluorine has 7 valence electrons, it belongs to the same group (Group 17, halogens) and is chemically similar to Chlorine.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Ar has 8 valence electrons.\n• Option (C): N has 5 valence electrons.\n• Option (D): P has 5 valence electrons.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 25000),
    ),
    Question(
      id: "sci_ch5_ex_q06",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 6] The positions of three elements A, B, and C in the Periodic Table are shown below:\nGroup 16: -, -, B\nGroup 17: -, A, -, C\nWhich statement correctly describes the properties of A, B, and C?",
      options: const [
        QuestionOption(id: "A", text: "A is a non-metal; C is less reactive than A; C is smaller in size than B; and element A forms an anion (\$\\text{A}^-\$).", isCorrect: true),
        QuestionOption(id: "B", text: "A is an alkali metal; C is more reactive than A; C is larger in size than B; and A forms a cation.", isCorrect: false),
        QuestionOption(id: "C", text: "A is a metalloid; C is a noble gas; B forms cations; and C is identical in size to B.", isCorrect: false),
        QuestionOption(id: "D", text: "C is more reactive than A because non-metallic reactivity increases down every group.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) A is a non-metal; C is less reactive than A; C is smaller in size than B; and element A forms an anion (\$\\text{A}^-\$).\n\nScientific Principle / Key Concept:\n• Table Position:\n  - Group 16: Period 2 (-), Period 3 (-), Period 4 (B)\n  - Group 17: Period 2 (-), Period 3 (A), Period 4 (-), Period 5 (C)\n1. Metal or Non-metal: Element A is in Group 17 (Halogens). Halogens have 7 valence electrons and high electronegativity, so A is a NON-METAL.\n2. Reactivity of C vs A: In Group 17, non-metallic reactivity depends on electron-gaining ability. As we move down the group, atomic size increases, effective nuclear pull decreases, and tendency to gain electrons decreases. Hence, C is LESS REACTIVE than A.\n3. Size of C vs B: B is in Group 16 and C is in Group 17 (or C is in a period below, but comparing across: atomic radius decreases from left to right across a period because nuclear charge increases, pulling electrons closer; hence Group 17 element C is smaller than Group 16 element B of the same/adjacent period).\n4. Ion formed by A: Group 17 element A has 7 valence electrons; it gains 1 electron to complete its octet, forming an ANION (\$\\text{A}^-\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Inverts non-metal, reactivity, and ion type.\n• Option (C): Misidentifies group identities.\n• Option (D): Non-metallic reactivity decreases down a group.",
      difficultyLevel: DifficultyLevel.hots,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 26000),
    ),
    Question(
      id: "sci_ch5_ex_q07",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 7] Nitrogen (atomic number 7) and phosphorus (atomic number 15) belong to group 15 of the Periodic Table. Write their electronic configurations. Which of these will be more electronegative and why?",
      options: const [
        QuestionOption(id: "A", text: "Nitrogen: \$2, 5\$; Phosphorus: \$2, 8, 5\$. Nitrogen is more electronegative because its atomic radius is smaller, allowing the nucleus to attract shared electrons more strongly.", isCorrect: true),
        QuestionOption(id: "B", text: "Nitrogen: \$2, 5\$; Phosphorus: \$2, 8, 5\$. Phosphorus is more electronegative because it has more protons in its nucleus.", isCorrect: false),
        QuestionOption(id: "C", text: "Nitrogen: \$2, 8\$; Phosphorus: \$2, 8, 8\$. Both have identical electronegativity.", isCorrect: false),
        QuestionOption(id: "D", text: "Neither is electronegative because Group 15 elements are all electropositive metals.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Nitrogen: \$2, 5\$; Phosphorus: \$2, 8, 5\$. Nitrogen is more electronegative because its atomic radius is smaller, allowing the nucleus to attract shared electrons more strongly.\n\nScientific Principle / Key Concept:\n• Electronic configurations:\n  - Nitrogen (\$Z=7\$): \$2, 5\$ (2 occupied shells: K, L)\n  - Phosphorus (\$Z=15\$): \$2, 8, 5\$ (3 occupied shells: K, L, M)\n• Electronegativity is the tendency of an atom to attract shared pair of electrons toward itself.\n• Moving down Group 15 from N to P, an additional electron shell is added, which increases atomic size and nuclear shielding.\n• Because nitrogen has a smaller atomic size, its nucleus is closer to the valence shell and exerts a much stronger pull on shared electron pairs.\n• Therefore, Nitrogen is more electronegative than Phosphorus.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Incorrect. Distance and shielding overcome extra nuclear charge down a group.\n• Option (C): Incorrect electronic configurations.\n• Option (D): Incorrect. N and P are non-metals.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 27000),
    ),
    Question(
      id: "sci_ch5_ex_q08",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 8] How does the electronic configuration of an atom relate to its position (period and group) in the Modern Periodic Table?",
      options: const [
        QuestionOption(id: "A", text: "The number of occupied electron shells determines the Period number, and the number of valence electrons determines the Group number (Group = valence electrons for 1, 2; Group = \$10 + \\text{valence electrons}\$ for 3 to 8).", isCorrect: true),
        QuestionOption(id: "B", text: "The total number of neutrons determines the period, and total protons determine the group.", isCorrect: false),
        QuestionOption(id: "C", text: "The period number is always equal to the atomic mass divided by 10.", isCorrect: false),
        QuestionOption(id: "D", text: "Electronic configuration has no relationship with position in the Modern Periodic Table.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) The number of occupied electron shells determines the Period number, and the number of valence electrons determines the Group number (Group = valence electrons for 1, 2; Group = \$10 + \\text{valence electrons}\$ for 3 to 8).\n\nScientific Principle / Key Concept:\nRelationship between Electronic Configuration and Periodic Position:\n1. Period Number:\n• The number of occupied electron shells in an atom determines its period.\n• Example: Sodium (\$2, 8, 1\$) has 3 shells (K, L, M) \$\\rightarrow\$ Period 3.\n2. Group Number:\n• The number of valence electrons in the outermost shell determines its group:\n  - If valence electrons = 1 \$\\rightarrow\$ Group 1\n  - If valence electrons = 2 \$\\rightarrow\$ Group 2\n  - If valence electrons = 3 to 8 \$\\rightarrow\$ Group = \$10 + \\text{valence electrons}\$ (e.g., Chlorine with 7 valence electrons is in Group \$10 + 7 = 17\$).\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Neutrons do not determine periods.\n• Option (C): Mass is not used.\n• Option (D): Electronic configuration is the fundamental basis of the table.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 28000),
    ),
    Question(
      id: "sci_ch5_ex_q09",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 9] In the Modern Periodic Table, calcium (atomic number 20) is surrounded by elements with atomic numbers 12, 19, 21, and 38. Which of these have physical and chemical properties resembling calcium?",
      options: const [
        QuestionOption(id: "A", text: "Elements with atomic numbers 12 (Magnesium, \$\\text{Mg}\$) and 38 (Strontium, \$\\text{Sr}\$)", isCorrect: true),
        QuestionOption(id: "B", text: "Elements with atomic numbers 19 (Potassium) and 21 (Scandium)", isCorrect: false),
        QuestionOption(id: "C", text: "All four elements (12, 19, 21, 38) because they are directly adjacent in the grid.", isCorrect: false),
        QuestionOption(id: "D", text: "Only element 21 (Scandium) because it is the next consecutive integer.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Elements with atomic numbers 12 (Magnesium, \$\\text{Mg}\$) and 38 (Strontium, \$\\text{Sr}\$)\n\nScientific Principle / Key Concept:\n• Elements in the same group possess the same number of valence electrons and exhibit similar physical and chemical properties.\n• Electronic configurations:\n  - Calcium (\$Z=20\$): \$2, 8, 8, 2\$ (2 valence electrons, Group 2)\n  - Element \$12\$ (Magnesium): \$2, 8, 2\$ (2 valence electrons, Group 2)\n  - Element \$38\$ (Strontium): \$2, 8, 18, 8, 2\$ (2 valence electrons, Group 2)\n  - Element \$19\$ (Potassium): \$2, 8, 8, 1\$ (Group 1)\n  - Element \$21\$ (Scandium): \$2, 8, 9, 2\$ (Group 3)\n• Since elements with atomic numbers 12 and 38 belong to the same group (Group 2) as Calcium, they share physical and chemical properties resembling Calcium.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Potassium and scandium have 1 and 3 valence electrons.\n• Option (C): Period neighbors differ chemically.\n• Option (D): Next integer is in a different group.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 29000),
    ),
    Question(
      id: "sci_ch5_ex_q10",
      subject: Subject.science,
      chapterId: "sci_ch_05_life_processes",
      questionText: "[NCERT Exercise 10] Which statement correctly compares and contrasts the arrangement of elements in Mendeléev's Periodic Table versus the Modern Periodic Table?",
      options: const [
        QuestionOption(id: "A", text: "Mendeléev's Table is based on increasing atomic masses with 8 groups (divided into sub-groups A and B), could not position isotopes, and had anomalous inverted mass pairs; the Modern Periodic Table is based on increasing atomic numbers with 18 distinct vertical groups and 7 horizontal periods, naturally accommodating isotopes and resolving all mass inversions.", isCorrect: true),
        QuestionOption(id: "B", text: "Mendeléev's Table used atomic numbers, while the Modern Table reverted to atomic masses.", isCorrect: false),
        QuestionOption(id: "C", text: "Both tables have identical 18 groups and placed noble gases in Group 1 with alkali metals.", isCorrect: false),
        QuestionOption(id: "D", text: "Mendeléev's Table arranged elements into octaves of musical notes, while the Modern Table uses atomic volume triads.", isCorrect: false),
      ],
      stepByStepSolution: "Correct Answer: (A) Mendeléev's Table is based on increasing atomic masses with 8 groups (divided into sub-groups A and B), could not position isotopes, and had anomalous inverted mass pairs; the Modern Periodic Table is based on increasing atomic numbers with 18 distinct vertical groups and 7 horizontal periods, naturally accommodating isotopes and resolving all mass inversions.\n\nScientific Principle / Key Concept:\nComparison:\n1. Basis of Classification:\n• Mendeléev's Table: Atomic mass (Properties are periodic function of atomic masses).\n• Modern Periodic Table: Atomic number (Properties are periodic function of atomic numbers).\n2. Structure:\n• Mendeléev: 8 Groups (subdivided into A and B sub-groups) and 6 Periods.\n• Modern Table: 18 Vertical columns (Groups) and 7 Horizontal rows (Periods).\n3. Anomalies & Isotopes:\n• Mendeléev could not assign a fixed place to hydrogen or isotopes, and had anomalous pairs (Co before Ni, Te before I).\n• Modern Table places isotopes in the same position and puts Co (\$Z=27\$) before Ni (\$Z=28\$) without anomaly.\n\nDetailed Distractor & Misconception Analysis:\n• Option (B): Inverts the historical basis.\n• Option (C): Noble gases are in Group 18, never Group 1.\n• Option (D): Confuses Newlands with Mendeléev.",
      difficultyLevel: DifficultyLevel.medium,
      status: QuestionStatus.approved,
      submittedBy: '00000000-0000-0000-0000-000000000001',
      reviewedBy: '00000000-0000-0000-0000-000000000001',
      createdAt: DateTime.fromMillisecondsSinceEpoch(1727200000000 + 30000),
    ),
  ];
}
